### ISSUE TITLE
Raise Max Google Drive file count above 999

### ISSUE THREAD

**Issue by NotYourAlejandro** [nextcloud/integration_google#104]
Hello,

I was testing out the Google data migration feature, and there is one major issue I am finding here.

When importing files from a drive that has more than 999 files, the counter keeps going above that. Along with that, the percentage complete corresponds with that counter, printing statements such as "2030 files imported (203%)".

![Screenshot from 2022-04-04 14-23-22](https://user-images.githubusercontent.com/19955560/161634949-cecadfff-2826-4e24-bbc7-100c1df0bea2.png)

Thanks for your time, and I appreciate the work so far on the project!

**Comment by eneiluj** [comment]
This was fixed by https://github.com/nextcloud/integration_google/pull/94 but not released yet. Next release is coming soon.
