### ISSUE TITLE
Files not loading

### ISSUE THREAD

**Issue by swforge-0** [nextcloud/integration_google#106]
Hello, I have this problem:

google account connects, clings to the disk, but does not download anything https://prnt.sc/dodGyoaxWOgx , and hangs at 0% https://prnt.sc/ZW-lyQKray5J . Requests are visible in google statistics, errors do not appear https://prnt.sc/30q4L4mzbLTW. API access for all necessary services - open. The ignored shared files option does not change the situation in any way. During one of the experiments in the /Google Drive directory, a directory structure similar to the structure in google drive was created, but not a single file was uploaded

**Comment by k-popov** [comment]
I used to have similar issue. GDrive import runs as background job so check you have cron/webcron configured and jobs are running.

Tasks may be listed by `select * from oc_jobs order by last_checked asc;`. If you're running webcron and not system cron consider running the call to `cron.php` more frequently - in my case Drive import jobs were just far back in the list of jobs to execute.

**Comment by julien-nc** [comment]
Feel free to reopen this if needed.
