### ISSUE TITLE
Google data migration - contacts' photos not migrated over

### ISSUE THREAD

**Issue by silverdr** [nextcloud/integration_google#107]
Hi, I used “Google data migration” to migrate contacts and calendars. Things mostly went well, but… all contacts lost their photos! Google has them (photos), Nextcloud does not. Is this a “known bug/limitation”? Any method(s) to migrate contacts with photos?

**Comment by eneiluj** [comment]
Hi, I think this is fixed now. It used to determine the photo type from the file URL but it is far from reliable. The type is now determined from the photo request response headers.

You can try v1.0.7-2-nightly or wait for the next release which is coming soon.
