### ISSUE TITLE
Calendar dont Sync

### ISSUE THREAD

**Issue by DJ3vil** [nextcloud/integration_google#109]
Hey, ive got all the config right, i was able to connect my Calendar but i dont see any changes made in nextcloud sync with google Calendar. Also it seems it dont work in the other direktion. Right now i cant see any logs say there is an error

**Comment by DJ3vil** [comment]
Ive ive reimport the Calendar i can see the changes made in Google Calendar (basicly an manuel download again)

**Comment by julien-nc** [comment]
This app does not provide any sync feature. This is just a one-time calendar import.

Next release will update events that already exist in NC instead of recreating everything on import.

**Comment by LokeYourLord** [comment]
> This app does not provide any sync feature. This is just a one-time calendar import.
> 
> Next release will update events that already exist in NC instead of recreating everything on import.

Will there ever be a sync feature? That would make it quite useful since you can sync calendar events made in NextCloud to Google Calendar and vice versa, allowing for a lot of flexibility.
