### ISSUE TITLE
Unknown error when Google authentication

### ISSUE THREAD

**Issue by DayDve** [nextcloud/integration_google#110]
I created OAuth like this [Credentials OAuth consent screen different to installation doc](https://github.com/nextcloud/integration_google/issues/48#issuecomment-775293092).
However, when trying to authenticate using Oauth, I get an error:

> Sign in with Google
> Something went wrong
> Sorry, something went wrong there. Try again.

With the following url: "https://accounts.google.com/info/unknownerror"
And with a button "Next"

When i pressing "next", i redirecting to page with 400 error:  

> 400. That’s an error.
> The server cannot process the request because it is malformed. It should not be retried. That’s all we know.

![google error](https://www.google.com/images/errors/robot.png)

what am i doing wrong?

**Comment by Jolg42** [comment]
I also got this error on Firefox and didn't find a way to make it work but it went away when I used Chrome.
Maybe that helps 🤞🏼

**Comment by bardo** [comment]
Same issue with Firefox, Chromium worked.

**Comment by coltenkrauter** [comment]
The same thing happened to me. On my TrueNAS Scale, after setting up Nextcloud, I added Google Integration. I clicked Using Mozilla Firefox, I went to `Data migration` in the Nextcloud settings and the Oauth flow failed with,

>  Sorry, something went wrong there. Try again.

I did it in Chrome and everything worked fine.

**Comment by marcelklehr** [comment]
Mh, I cannot reproduce this. Works fine with Firefox 113 here.

**Comment by FranLegon** [comment]
I have the same issue in Chrome. Has anyone solved it?
