### ISSUE TITLE
Cannot import contacts

### ISSUE THREAD

**Issue by LightTemplar** [nextcloud/integration_google#111]
Cannot import contacts, they are don't even in under other options and if I open them, there is a following message: 
`Failed to get number of Google contacts: "ServerException|ClientException, message:Client error: `GET https:\/\/people.googleapis.com\/v1\/people\/me\/connections?personFields=names&pageSize=100` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"code\": 403,\n \"message\": \"People API has not been used in project 509922505792 before or it is dis (truncated...)\n status code: 403"✖`

**Comment by LightTemplar** [comment]
There is still this error. Google made "People API" and the plugin should now use it.
Got same error today:
```
Failed to get number of Google contacts: "ServerException|ClientException, message:Client error: `GET https:\/\/people.googleapis.com\/v1\/people\/me\/connections?personFields=names&pageSize=100` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"code\": 403,\n \"message\": \"People API has not been used in project 509922505792 before or it is dis (truncated...)\n status code: 403"
```

**Comment by marcelklehr** [comment]
@LightTemplar Thank you for responding! :) I will look into it.

**Comment by marcelklehr** [comment]
Hello! I've just tried to reproduce this and I am unable to. Contacts import works fine for me. Please make sure you configure your google oauth app correctly to allow access to contacts.
