### ISSUE TITLE
Photo migration stuck after nextcloud container restart

### ISSUE THREAD

**Issue by AtActionPark** [nextcloud/integration_google#116]
I have launched the migration without issues. 

After a couple of hours and a few thousand photos imported, I had to restart my nextcloud container after a server crash (nextcloud v 24.0.4).

The photos are detected on the google side and requests are sent regularly but nothing happens, import is stuck on 0 photos imported

Im getting the following payload back: 
{"importing_photos":true,"last_import_timestamp":0,"nb_imported_photos":0}

![image](https://user-images.githubusercontent.com/7009884/189149602-fe624a45-10bd-4e49-8c23-02e03492d1c7.png)

is there an expected action on my end after a restart?

thanks

FOR REFERENCE:
I'm using nextcloud from a docker compose file, steps to solve were the following:

Get in the db container
`docker exec -it nextcloud_db bash`

Get a mysql prompt
`mysql -uroot -p`

use the database as set up in your docker compose file
`use nextcloud;`

Check the oc_preferences table, find the row containing the value to toggle, and confirm it is set to 1

`select configKey, configValue from oc_preferences where configKey = "photo_import_running";`

Result: 
```
+----------------------+-------------+
| configKey            | configValue |
+----------------------+-------------+
| photo_import_running | 1           |
+----------------------+-------------+
```

Edit the value
`UPDATE oc_preferences SET configValue = 0 WHERE configKey = "photo_import_running";`

**Comment by lilfade** [comment]
see this: [the fix](https://github.com/nextcloud/integration_google/issues/35#issuecomment-1030504895)

**Comment by AtActionPark** [comment]
> see this: [the fix](https://github.com/nextcloud/integration_google/issues/35#issuecomment-1030504895)

Looks promising, thanks. 
I'm not quite sure how to proceed though, would you mind detailing the procedure a bit?

cheers

**Comment by lilfade** [comment]
Seems to be just a value change in the database settings table for your
user. I'm at work currently but can post the field name when i get home if
you don't get it by then.

**Comment by AtActionPark** [comment]
@lilfade 
please let me know if you can. I'm looking in tfe oc_users and oc_user_status tables but I dont see the flag, guess I'm not looking in the right place

**Comment by lilfade** [comment]
@AtActionPark sorry about that, oc_preferences is where it's at.

**Comment by AtActionPark** [comment]
@lilfade Thanks a lot, that did the trick <3

**Comment by julien-nc** [comment]
A fix is potentially coming in the next release. If you want to test it: https://github.com/nextcloud/integration_google/issues/35#issuecomment-1361381136

**Comment by marcelklehr** [comment]
This should be fixed since the second-to-last release. Let me know if it isn't.
