### ISSUE TITLE
Photos and Drive import doesn't use exif/created date

### ISSUE THREAD

**Issue by Sid127** [nextcloud/integration_google#119]
Facing a similar issue to #42 using Nextcloud v24 and google integration v1.0.8

**Comment by mynameisfiber** [comment]
I'm on Nextcloud v25 and Google Integration v1.0.8 and I'm seeing dates but no exif data!

**Comment by julien-nc** [comment]
This is fixed and will be available in the next release which is coming soon.

**Comment by mynameisfiber** [comment]
@julien-nc amazing. thank you! is there a process to add the exif data to already-imported photos?

**Comment by julien-nc** [comment]
@mynameisfiber Not really because there is no easy way to identify those with missing exif data.
