### ISSUE TITLE
Google Drive File ID is included in file name

### ISSUE THREAD

**Issue by Mezgrman** [nextcloud/integration_google#127]
As can be seen in [this line](https://github.com/nextcloud/integration_google/blob/bc4338a7bb94cf8bd2621dc99041d594e2ad32a8/lib/Service/GoogleDriveAPIService.php#L516), the Drive file import mangles the original file name by appending an ID.
This causes all the imported files to have this ID appended for no obvious reason. This makes it unacceptable as an import tool should not modify the data it imports.

**Comment by Mezgrman** [comment]
It seems that this was introduced in commit f24687a with no obvious reason.

**Comment by Mezgrman** [comment]
It seems that this was introduced by @akhil1508in commit f24687a with no obvious reason.

**Comment by Mezgrman** [comment]
It seems that this was introduced by @akhil1508 in commit f24687a with no obvious reason.

**Comment by akhil1508** [comment]
> It seems that this was introduced by @akhil1508 in commit [f24687a](https://github.com/nextcloud/integration_google/commit/f24687a4deaf9d7d974a86550644939836229aff) with no obvious reason.

Please check 3 [here](https://github.com/nextcloud/integration_google/pull/83#issue-1043189490)

Do suggest a better idea if you have :D

**Comment by Mezgrman** [comment]
Thanks for linking that, now I see the motivation. :)
First thing that comes to mind is to only append the ID in case a file of the given name already exists. This should be relatively easy to implement I think. I'll think about it

**Comment by julien-nc** [comment]
I think the best way to go would be to add a suffix only when there is a name conflict on the google side. I'll do it soon.

**Comment by julien-nc** [comment]
The "id" suffix is now only added for files that have a duplicated name in the remote directory. This is available in v1.0.9-4-nightly if you want to try it (which would be nice). Otherwise, it will be included in v1.0.9 which is coming soon.

**Comment by Mezgrman** [comment]
Wow, that was quick! How do I install the nightly?

**Comment by julien-nc** [comment]
You can replace the app directory (`nextcloud/apps/integration_google`) by the one in https://github.com/nextcloud/integration_google/releases/download/v1.0.9-4-nightly/integration_google-1.0.9-4-nightly.tar.gz

This is not destructive as there is no new migration step in this nightly. You can easily go back to the latest stable version by deleting the app directory and reinstalling from the app settings page.

**Comment by Mezgrman** [comment]
Will try, thanks!

**Comment by Mezgrman** [comment]
Installation worked, testing now. Another thing (although unrelated) I have noticed is that `getDriveSize` takes a really long time - I have around 132 GiB in ~80000 files in my drive. I had to increase the reverse proxy timeout for it to load 😅 but please don't see this as a complaint, I don't even know if it's fixable. I can just let the import run for a few days and it should be done, no problem. Just wanted to point it out! Thanks again for the super fast response to my report.

**Comment by Mezgrman** [comment]
Almost forgot the feedback! The import took 2 or 3 days, but worked fine, a few actual duplicate files got properly renamed, the rest kept their original names. 👍

**Comment by julien-nc** [comment]
Great! Thanks for the (not-so-late :grin:) feedback.
