### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jjisnow** [nextcloud/integration_google#13]
There is the error message "Could not download app integration_google" upon attempting to download the app from the app store.

Admin Logging is as follows:

`
Exception: Could not download app integration_google/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 445:OC\Installer->downloadApp("integration_google")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:OCA\Settings\Controller\AppSettingsController->enableApps([ "integration_google"], [])/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")/var/www/nextcloud/lib/private/AppFramework/App.php - line 152:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")/var/www/nextcloud/lib/private/Route/Router.php - line 308:OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { action: nu ... "})/var/www/nextcloud/lib/base.php - line 1009:OC\Route\Router->match("/settings/apps/enable")/var/www/nextcloud/index.php - line 37:OC::handleRequest()
`

There is a warning prior to the error as follows:

`Could not connect to appstore: cURL error 28: Connection timed out after 120001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Is there something I'm missing at all?

**Comment by eneiluj** [comment]
The appstore was down/slow. This is not related to this app. It should be fine now.
