### ISSUE TITLE
Drive import stuck at 0%

### ISSUE THREAD

**Issue by Schachte** [nextcloud/integration_google#130]
I can't get Google Drive import to move beyond 0%.

I've done the following:

- Enabled system Cron
- Manually triggered as `www-data` user
- Enabled Drive API

FWIW, I got a few photos to import from photos API as well as calendar. I can see that a few `list` requests were made from nextcloud credentials in Google API console. What else would be going on here? The total size is ~125GB. 

Nothing in logs. 

V 1.0.9
NC: 25

**Comment by livier** [comment]
I felled the same way, same versions. Seemed to not advance for long time. Went away for a while (a walk in the forest) and then it moved. A long while more for advancing and finishing. Here less than 2 GB to move. if you have 125 GB, it will be much longer for you than me. Take a week of  holidays before saying it does not move ...
Seriously I went here to see if someone else had the same problem, or report it. 
I think we are in the same case. Transfer is really very, very long. 
I have a Gdrive folder to follow for a 6 month course, I  hoped for a synchronizing tool. Seems it is a migration tool only, but please could it be reasonably not too slow, I will click on "Import" every week for the next month ...
