### ISSUE TITLE
"401 Unauthorized" after a week from initial setup

### ISSUE THREAD

**Issue by shalak** [nextcloud/integration_google#131]
Exactly 7 days ago, I've setup the Google Integration 1.0.9 in a fresh nextcloud-aio 25.0.3 installation.

Whole week I've experienced an issue with [import process getting stuck](https://github.com/nextcloud/integration_google/issues/51#issuecomment-1411265226). I was simply canceling and re-starting the process, and with every attempt I got a little bit more of data from Google Drive/Photos.

Today, when I wanted to go through the usual routine mentioned above, I couldn't - there was a toasty message mentioneing 401 showing up on my profile, and admin logs are showing:

```
Google API ServerException|ClientException error : Client error: `GET https://photoslibrary.googleapis.com/v1/albums?pageSize=50` resulted in a `401 Unauthorized` response: { "error": { "code": 401, "message": "Request had invalid authentication credentials. Expected OAuth 2 access (truncated...) status code: 401 body: { "error": { "code": 401, "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "status": "UNAUTHENTICATED" } } 
```

In the meantime,  0,92%  `drive.files.get` errors appeared in Google Console:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1536554/216952653-712d54c2-d4fb-427d-90cb-a4932e1d8656.png">

Am I doing something wrong? Like the token expires after a week, or something?

Also, what more important - can I safely "Disconnect from Google" in my profile and re-authenticate again, and the whole process will be able to pick up where it left off?

**Comment by Anas-Sherif** [comment]
You gotta enable the apis in the google cloud dashboard, check the instructions in the admin settings.

**Comment by Anas-Sherif** [comment]
> I did enable all of them.

after you do it you may need to logout of google from nextcloud and reauth.
