### ISSUE TITLE
nextcloud Google Synchronization failed to create a new sync

### ISSUE THREAD

**Issue by dodofox81** [nextcloud/integration_google#136]
Hi, I have installed Nextcloud 26. The server it's debian 11 with mariadb, apache2.
I have installed 2 apps:
Google integration and Google Synchronization
All work fine, I have connected my google account with api into my nextcloud. calendar, contact, drive ecc... imported correctly.
The problem it's when I try to click on SYNC CALENDAR. This function must to create a cron job to sync every 5 minutes google calendar with nextcloud. Well, it not work and it display this error:

ReflectionException: Method OCA\Google\Controller\GoogleAPIController::registerSyncCalendar() does not exist

I have try with another nextcloud installation ... same error. 

![immagine](https://user-images.githubusercontent.com/129279279/232738512-fdeef4af-a555-4f67-aad6-98a2bc990227.png)

When I click on SYNC:

![immagine](https://user-images.githubusercontent.com/129279279/232738805-1fd891ae-f46b-473c-85d7-31bb15e5883a.png)

![immagine](https://user-images.githubusercontent.com/129279279/232738967-8a796fb2-5954-49fa-a3f0-e91b0e42aab7.png)

**Comment by teambvd** [comment]
The 'synchronize' function is provided by the ]google synchronization](https://github.com/MarcelRobitaille/nextcloud_google_synchronization) app, not this integration app from NC. Issue may be caused by using both apps at once, which is [not recommended](https://github.com/MarcelRobitaille/nextcloud_google_synchronization#:~:text=This%20also%20means%20that%20this%20app%20should%20not%20be%20used%20at%20the%20same%20time%20as%20Google%20Integration)

**Comment by dodofox81** [comment]
No, you don't have understand. The problem it's another:
the cronjob to sync google cal into nextcloud server it's not created, so the autosync not start.

**Comment by AzureInformatique** [comment]
Same error for me with Google Google Synchronization 1.0.9 when I tried to Import a Calendar 
Nextcloud 26.0.1 
MariaDB 10.6
PHP 8.2

![Capture d’écran 2023-05-11 110448](https://github.com/nextcloud/integration_google/assets/124894927/d71553bf-982f-4d98-944a-79ca0d5348ed)

**Comment by marcelklehr** [comment]
Hello :)

This is not the google synchronization app. This is the integration_google app. This app does not offer any synchronization functionality. If you have problems with functionality provided by a different app, please go to the corresponding repository of the app you have problems with.
