### ISSUE TITLE
Photos import question.

### ISSUE THREAD

**Issue by sebvil** [nextcloud/integration_google#14]
Not sure if this is intended or not, but when I try importing from Google Photos, it only imports those photos I have placed in albums. I was just wondering if it is possible to import all photos, even those that are not in an album.

**Comment by eneiluj** [comment]
Thanks for the bug report!

As I don't use this service and the API does not provide a natural access to such photos, they were ignored. It's now fixed and will be included in next release.

Only way I found to get those photos is to remember all photo IDs when exploring/downloading albums, then getting the flat list of all photos and deducing that those we never saw are the ones outside albums...

When you'll have the next release, you can just launch another import, it will not download the photos you already imported.

**Comment by sebvil** [comment]
Thank you for your response! I look forward to the next release!

**Comment by eneiluj** [comment]
The v0.0.5 release is out. I'm very interested in your feedback. Thanks for your interest.

**Comment by sebvil** [comment]
I just tried it out, and it seems I was able to migrate all my photos successfully, so thank you for that! Only thing I noticed is the progress did not update and it was at 0% the whole time, so I had to go and check my Files app to make sure the photos were being migrated.

**Comment by eneiluj** [comment]
Are you saying the interface didn't tell you when it the import finished? You should get a notification when the import process finishes.

The import is done in chunks of 500 MB. So in your case, if the total size of missing photos was less than 500 MB, it's normal and expected to see a progress of 0% and then directly 100% after the first job has finished.

If you don't see the notification and you don't see the "import google photos" button again in the settings, we've got a problem.

I tested that a dozen times with different chunks sizes and different photo collection size, it always worked.

**Comment by sebvil** [comment]
I did receive the notification. I just checked and the total file size was in fact less than 500MB, so then it makes sense why I did not see the progress increase. Thanks for the help and this useful app!

**Comment by eneiluj** [comment]
Import progress is now "real time". On the server side, the counter is updated on each file/photo download (and not at the end of a job as it was before) and on the browser side, the values are updated every 10 seconds.

This will be included in next release.
