### ISSUE TITLE
Google Migration - Successfully connected but no state

### ISSUE THREAD

**Issue by aortmannm** [nextcloud/integration_google#141]
Hi, I was successfully setting up the api and the data migration connection was established. I have no errors in the log files (nothing since data migration) and I just see no progress.

Any Idea what can cause this issue?

![image](https://github.com/nextcloud/integration_google/assets/3414298/7d366de1-5bbd-4bea-9e28-78250780d167)

**Comment by aortmannm** [comment]
I have changed no the loglevel that I get all information but there seems just to be two requests that sucess as debug message

![image](https://github.com/nextcloud/integration_google/assets/3414298/45f09b02-6dc4-4497-99af-2775bc67d402)

**Comment by Brodiyaga** [comment]
same problem

**Comment by aaemon** [comment]
facing same issue

**Comment by cmmmota** [comment]
same here

**Comment by Huweh** [comment]
Same issue , connected but no state

**Comment by bonzo72** [comment]
Same issue, just started recently. Will update with environment soon

**Comment by bardo** [comment]
Same here. Just to add to the bunch of already varied configurations, I am using Nextcloud 26.0.1.1 in a SmartOS zone, PHP 8.2.5 and a Postgres database. Happy to share more details if needed.

**Comment by WesleyCeraso** [comment]
Same here.

**Comment by hlugt** [comment]
And here....

**Comment by PabloMz85** [comment]
Running in the same issue

**Comment by jaazrider** [comment]
Same here...

Nextcloud 26.0.1
Raspberry Pi 4 Model B Rev 1.4, 4 cores
Linux 5.15.0-1028-raspi on aarch64
Ubuntu Linux 22.04.2
Mem 3.69 GiB used / 3.51 GiB cached / 7.57 GiB total
PHP Version: 8.1.2
Database mysql 10.6.12 Size: 3 GB

**Comment by Jordfoz16** [comment]
Same issue

Unraid: 6.11.5
Linux 5.19.17
Mem 16GB
PHP 8.1.19
MySQL 10.6.13

**Comment by bardo** [comment]
@julien-nc maybe you can point us in the right direction?

(Apologies for the direct ping, I'm not a fan of tagging people, but this is a widespread breaking issue that seems to have gone under the radar.)

**Comment by Stooovie** [comment]
Same

**Comment by infectedrusskiy** [comment]
I'm having this problem too; in case you need someone for testing/verification.

**Comment by carcawey** [comment]
The same thing happens to me

![IMG_20230527_112822](https://github.com/nextcloud/integration_google/assets/134774699/0d6f70e0-c1d1-45ad-adb2-925bfb939837)

It appears connected to me, but the rest is blank.

**Comment by mecpcanada** [comment]
+1

**Comment by edricwb** [comment]
+1

**Comment by marcelklehr** [comment]
Should be fixed in v2.0.2
