### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by ste7enm** [nextcloud/integration_google#147]
### Which version of integration_google are you using?

2.0.2

### Which version of Nextcloud are you using?

26.0.2

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 114.0.5735.106

### Describe the Bug

Attempting to set up the app, I go to the Data migration area and click Sign in with Google and get the error `Access blocked: This app’s request is invalid` `Error 400: redirect_uri_mismatch`.
![Screenshot 2023-06-14 at 11 31 44 AM](https://github.com/nextcloud/integration_google/assets/9658882/11c110f2-f3d7-4772-bb8b-9a08f88cf028)

This happens if I'm in a Google instance where I'm already signed in or in an Incognito window that would typically redirect me to a net new Google sign-in page upon clicking the button, presumably.

### Expected Behavior

I would expect it to redirect me to the Google sign-in page.

### To Reproduce

Seems fundamental – I updated the app, enabled it, went to configure and got the error.

**Comment by marcelklehr** [comment]
Hello 👋 

Did you set the redirect uri in Google that the app tells you in the admin settings?

**Comment by elpraga** [comment]
I was getting this error today as well, but I was able to fix it by following the steps in Nextcloud admin "Connected accounts" setting.

**Comment by ste7enm** [comment]
Yes, you can consider this closed – it was the `Authorized redirect URI` that wasn't set correctly. Thanks for your support.
