### ISSUE TITLE
Photo Migration 403 from Google

### ISSUE THREAD

**Issue by tincanfury** [nextcloud/integration_google#149]
### Which version of integration_google are you using?

2.0.2

### Which version of Nextcloud are you using?

26.0.1

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome

### Describe the Bug

attempting to import/read Google Photos gives the following error:

Failed to get number of Google photos: "ServerException|ClientException, message:Client error: `GET https:\/\/photoslibrary.googleapis.com\/v1\/albums?pageSize=50` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"code\": 403,\n \"message\": \"Photos Library API has not been used in project 86909678758 before or it (truncated...)\n status code: 403"

if I go to the URL directly I get the following message from Google,
"404. That’s an error.

The requested URL /v1//albums?pageSize=50 was not found on this server. That’s all we know."

### Expected Behavior

photos get imported

### To Reproduce

Personal Settings>Data Migration

**Comment by tincanfury** [comment]
and immediately after trying to go back to my Nextcloud files I am now no longer able to access Nextcloud, 

"This site can’t be reachedpadresd.elfuriorojo.com took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT"

So I don't know what this app did...

**Comment by vymvn** [comment]
As the instructions in the "Connected accounts" say:

>  Finally, go to "APIs & Services" => "Library" and add the following APIs: "Google Drive API", "Google Calendar API", "People API" and "Photos Library API". 

I think you missed this step.

**Comment by cdedert** [comment]
> As the instructions in the "Connected accounts" say:
> 
> > Finally, go to "APIs & Services" => "Library" and add the following APIs: "Google Drive API", "Google Calendar API", "People API" and "Photos Library API".
> 
> I think you missed this step.

I did do this step and added the above APIs and am still having the same error.
