### ISSUE TITLE
OAuth2 Error: redirect_uri_mismatch Bad Request

### ISSUE THREAD

**Issue by ChrisKar96** [nextcloud/integration_google#15]
Hi,

I need some help with the OAuth2 authorization process, because I've been trying to set it up for days and I can't realize what I'm doing wrong. I installed the plugin at version 0.0.5 and have since updated to 0.0.7, without ever being able to log in my account (or anyone else in my organization)

The error I get is the following: 

Google connection error: Error getting OAuth access token. Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response: { "error": "redirect_uri_mismatch", "error_description": "Bad Request" } 

At first I though it was a simple error and that I made a mistake in Google API Console, when I set up the credentials, even though I followed the given hints exactly, and I have created Google API credentials in the past without problems.

I will try to include as many details as I can. Nextcloud is installed with a docker-compose configuration, alongside nginx, certbot and mariadb, at it's own subdomain, so there is only https access - http is redirected to https - at _nextcloud.domain.tld_.

In Google APIs I created the credentials and used `https://nextcloud.domain.tld` for **Authorized JavaScript origins** and `https://nextcloud.domain.tld/apps/integration_google/oauth-redirect` for **Authorized redirect URIs**. 
I enabled the specified APIs. 
At _Oauth Consent Screen_, **Authorized domains** contains just _domain.tld_. I added all the scopes the used APIs provided. This is the only thing I did that is not mentioned in the hints, but I tried without adding the scopes too and it didn't make a difference. 
I have entered the correct Client ID and Client Secret in the app's settings in nextcloud.

So, when I press the "Connect to Google" button, I see a GET request at `https://accounts.google.com/o/oauth2/v2/auth?client_id={{my-client-id}}&redirect_uri=https://nextcloud.domain.tld/apps/integration_google/oauth-redirect&response_type=code&access_type=offline&prompt=consent&state=fiyzu71f1j&scope=openid profile https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events.readonly https://www.googleapis.com/auth/contacts.readonly https://www.googleapis.com/auth/photoslibrary.readonly https://www.googleapis.com/auth/drive.readonly`. The redirect_uri in the GET request is EXACTLY the same as in **Authorized redirect URIs** in Google API Console. Despite that, I get the error I mentioned above.

I have tried adding the redirect uri with and without a trailing slash '/' and using https and http, but none worked and I think it shouldn't have anyways, since I use only https and the redirect_uri in the GET request doesn't have a trailing slash, so the correct one must be the one I currently use.

I tried waiting half a day before trying to sign in, to see if I just had to wait for Google APIs syncing the changes in the project, but that didn't help either.

Do you have any suggestions? How can I proceed to debug the error?

Thanks in advance.

**Comment by eneiluj** [comment]
Problem is most likely that after you've been successfully redirected, the last request done to google is providing an incorrect redirect uri because this one is generated on the server side so it is most likely using http in your case... I've seen that problem with Jira and Mastodon. I'll solve that and keep you informed.

Thanks for the bug report.

**Comment by eneiluj** [comment]
Could you try v0.0.8?

**Comment by ChrisKar96** [comment]
Thank you for the very fast response!

After updating to 0.0.8 the error is `400 Bad Request response: { "error": "invalid_request", "error_description": "Missing parameter: redirect_uri" } `

**Comment by eneiluj** [comment]
> I was able to log in for the first time!

Nice!

> I still get an error

Hmmm looking back to your previous comments, it seems you played with the OAuth app config:

> but I tried without adding the scopes too and it didn't make a difference

Did you double check your google OAuth app config in google developer console? It seems like the problem comes from there.

**Comment by eneiluj** [comment]
To make sure everything is refreshed when you make changes to the OAuth app (on google side), make sure you log out your account (on google) and disconnect in Nextcloud settings.

**Comment by ChrisKar96** [comment]
I am currently trying to debug this, as I am not able to sync from Google Drive. I get the error message that " 54 files in Google Drive (1 MiB) Your Google Drive is bigger than your remaining space left (0 B)"
It seems that in /src/components/PersonalSettings.vue, the "freeSpace" variable is set only by getNbGooglePhotos(), so if I can't (or don't want) to use this API, I can't get files from GDrive either. I mention this in case it's not intended behavior and needs to be fixed. 

In my Google Console Dashboard I can see the calls to all the other APIs but not this one, so I will try to sort this out and get back to you.
![image](https://user-images.githubusercontent.com/20391880/96704467-ccfeab00-139c-11eb-8a5e-eeeda650d4ff.png)

**Comment by eneiluj** [comment]
> I mention this in case it's not intended behavior and needs to be fixed

Yep, fixed. Will be in next release.

Anyway, I'm pretty sure the photo API problem is on your side. I really think the token stored in Nextcloud was produced while photo API was missing from the OAuth app. That's why you should lot out of google: to make sure you get a fresh token.

Here is a complete list of advice :grin: :

1. Double check you added the 4 APIs (it seems that you did when looking at your stats)
2. Log out on both sides (on google website and in Nextcloud settings) and double check the permissions you grant on the consent screen when connecting to google in Nextcloud.
3. If it still does not work, log out of everything, then just create another entry in google dev console "credentials", only set the "Authorized redirect URI", (the javascript origin is useless here) then set the new "Client ID" and "Client secret" in Nextcloud admin settings.

**Comment by ChrisKar96** [comment]
Unfortunately, it's not working for me...

I deleted the whole project and started again in the below order.

1. Create new project
2. Enable all 4 APIs
3. Create Consent Screen and enable all 55 available scopes. (I can see the 4 scopes by Photos Library API)
4. Create the credentials using only "Authorized redirect URI" and set the new "Client ID" and "Client secret" in Nextcloud admin settings.
5. Log out of both Google account and Nextcloud
6. Open Private Window, just to be extra safe. Log in Nextcloud, try to log in via OAuth in Google account (The GET request to Google includes this in the scopes "https://www.googleapis.com/auth/photoslibrary.readonly". I read in the docs that this should indeed be enough)
7. I see the new project name so it has definitely changed.
8. The consent screen that asks to confirm giving permissions for the APIs includes (just like it did in the previous project) the Photos Library API permissions.
9. OAuth succeeds but I get PERMISSION DENIED for Photos

The API usage is the same as before
![image](https://user-images.githubusercontent.com/20391880/96719960-cf6bff80-13b2-11eb-99b2-d88b7ddfb7e0.png)
Photos requests don't appear.

I can't imagine anything else to try on my end.

**Comment by eneiluj** [comment]
There is no need to configure the consent screen in dev console. Scopes are listed in connection request done by Nextcloud. That's why I don't mention it in the admin settings hint.

I don't know what is happening to you... Only remaining hypothesis: configuring the consent screen and adding all 55 scopes is the problem. I don't see any other possible reason.

**Comment by ChrisKar96** [comment]
It finally dawned on me! 

It was kind of stupid of me for not thinking of this earlier but not super obvious, and it really highlights the importance of 4a59b3b47cd20b0143c9367969d5f50cc889052c you did earlier.

My organization's Gsuite had Google Photos App disabled for everyone, since it's not a core Gsuite App. After enabling it, the error disappeared and I can import files from GDrive. 
I guess when the next release goes live, I can disable Photos again and have no problems? Maybe it will print the API error again, but I will be able to use Import from GDrive regardless.

Thanks for all the amazing and fast support.

**Comment by eneiluj** [comment]
Nice!

v0.0.9 is out.

> Maybe it will print the API error again, but I will be able to use Import from GDrive regardless

Exactly. Photo section will just be hidden. Feel free to reopen this issue if necessary.
