### ISSUE TITLE
Photos and Drive import stuck at 0%

### ISSUE THREAD

**Issue by isti2415** [nextcloud/integration_google#150]
### Which version of integration_google are you using?

2.0.2

### Which version of Nextcloud are you using?

27.0.0

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Microsoft Edge

### Describe the Bug

The import is stuck at 0% and Logging shows no relevant logs.

### Expected Behavior

Data from my Google Photos and Google Drive is supposed to be imported?

### To Reproduce

Logged into google account and pressed Import Google Photos and Import Google Drive. 

[https://ibb.co/8BGbwsx](url)

**Comment by gbcatrinoiu** [comment]
I have the same issue. There is no error in the console or in the logs but the files are not getting imported.

**Comment by Tetricz** [comment]
I also had this issue on Nextcloud 27.0.1
Google app is in testing with the following API enabled.

- Google Drive API
- Google Calendar API
- Photos Library API
- People API

I noticed, that this doesn't download the items until the next background job runs. Perhaps check `Administration > Basic Settings` to see if the background job is running. I use cron
