### ISSUE TITLE
Google Synchronization causes javascript error and  doesn't work

### ISSUE THREAD

**Issue by gianlukk** [nextcloud/integration_google#158]
### Which version of integration_google are you using?

Google Synchronization	1.0.9

### Which version of Nextcloud are you using?

NextCloudPi 26.0.3

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Google Chrome

### Describe the Bug

Probably mistaking, I first installed Google Synchronization before Google Integration. 
Hitting the button "Sync Now" a right top notify said me the background job was registered and everything seemed working normally , but nothing happened and no calendar was updated or imported.
Then i installed Google Integration and hitting the button "Importa calendario" it soon gived me Javascript error.
I realized I was wrong, and i disabled and uninstalled Google Synchronization.
Google integration started working fine, and imported correctly two of my Google Calendar.
I was sure I had solved the problem, and i downloaded and enabled again Google Synchronization.
Unexpectedly, now was Google Synchronization to cause javascript error, as shown below

![image](https://github.com/nextcloud/integration_google/assets/145855116/c91107c1-32ae-4902-8c22-838ef1703f37)

Is there an error or is the problem caused by my non-linear installation?

### Expected Behavior

I expect that hitting the button Sync Now the calendars were synchronized without errors

### To Reproduce

The error occurs when I press the Sync Now button

**Comment by marcelklehr** [comment]
Hello @gianlukk 

> Which version of integration_google are you using?
> 
> Google Synchronization 1.0.9

This is not the Google Synchronization repository. We are not in any way affiliated with the Google Synchronization app. If you want to use Google Integration, we recommend to disable Google Synchronization. If you want to use Google Synchronization, please report issues with their bug tracker.

Thank you.
