### ISSUE TITLE
Google Error

### ISSUE THREAD

**Issue by rustyaventador** [nextcloud/integration_google#16]
Dear, I can't do much with this message. What exactly does it mean? Thank you very much. Best regards and stay healthy. Neo

Fehler beim Abrufen der Kalender-Liste: "Client error: `GET https:\/\/www.googleapis.com\/calendar\/v3\/users\/me\/calendarList` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"code\": 403,\n \"message\": \"Google Calendar API has not been used in project 838129323555 before or (truncated...)\n"✖Fehler beim Abrufen der Google Drive-Informationen: "Client error: `GET https:\/\/www.googleapis.com\/drive\/v3\/about?fields=%2A` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"usageLimits\",\n \"reason\": \"accessNotConfigured\",\n \"message\": \"Acces (truncated...)\n"✖Fehler beim Abrufen der Anzahl der Google-Kontakte: "Client error: `GET https:\/\/people.googleapis.com\/v1\/people\/me\/connections?personFields=names&pageSize=100` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"code\": 403,\n \"message\": \"People API has not been used in project 838129323555 before or it is dis (truncated...)\n"✖Fehler beim Abrufen der Anzahl der Google-Fotos: "Client error: `GET https:\/\/photoslibrary.googleapis.com\/v1\/mediaItems?pageSize=100` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"code\": 403,\n \"message\": \"Photos Library API has not been used in project 838129323555 before or i (truncated...)\n"

**Comment by strugee** [comment]
It means you need to enable the Calendar API, Photos API, People API, and Drive API in the Google Developer Console. There's instructions in this app's admin page.

**Comment by rustyaventador** [comment]
@strugee many thanks. That was it. Thank you very much and stay healthy. Many greetings Neo
