### ISSUE TITLE
0 files imported (0%)

### ISSUE THREAD

**Issue by enekux** [nextcloud/integration_google#162]
### Which version of integration_google are you using?

2.1.0

### Which version of Nextcloud are you using?

v27.1.4

### Describe the Bug

Google Drive is not syncing and it shows "0 files imported (0%)"

### Expected Behavior

To sync all files

### To Reproduce

Connect with a Google Account which has access to all the required APIs and sync

**Comment by enekux** [comment]
the only error message I get in the nextcloud.log is the next:

```
{"reqId":"GmzweUJzBGHofXLUyEvO","level":2,"time":"2023-12-04T11:47:02+00:00","remoteAddr":"10.10.253.1","user":"f55fd350-3356-11ec-946c-a2e9d659703a","app":"integration_google","method":"GET","url":"/apps/integration_google/photo-number","message":"Google API error getting media items list to get photo number, no \"mediaItems\" key in []","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"integration_google"}}
```

**Comment by cylon56** [comment]
I'm experiencing the same bug. I can import Google contacts but Drive and Photo imports are still at 0%. I would love to get some answers on how to resolve it.

**Comment by brendanknights** [comment]
same here, same behaviour.
Google Contacts import fine, Calendar import fine
Photos and Drive stays at 0%

**Comment by luispinho** [comment]
Hello. I'm facing this issue as well, no warning/error logs in Nextcloud

**Comment by luispinho** [comment]
I was having the same issue but managed to get it working, turns out my configuration for running Cron jobs was off. Now that I set system Cron and made the it run every 5 minutes (according to the docs) the Google Photos import started. Here's some info from the [official Nextcloud documentation on background jobs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron). Also, if you're running inside Docker, you'll need to set the Cron job on the host machine.

**Comment by brendanknights** [comment]
> I was having the same issue but managed to get it working, turns out my configuration for running Cron jobs was off. Now that I set system Cron and made the it run every 5 minutes (according to the docs) the Google Photos import started. Here's some info from the [official Nextcloud documentation on background jobs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron). Also, if you're running inside Docker, you'll need to set the Cron job on the host machine.

Thanks Luis - you caused me to have another go at making sure my cron configs were correct. Took a little while to get working, but this is working on ubuntu server 22.04
*/5 * * * * /usr/bin/php8.1 -f /var/www/nextcloud/cron.php --define apc.enable_cli=1

I believe that I also needed to add the [acpu] declaration to the php.ini.
/etc/php/8.1/cli/php.ini
append to file:
[APCu]
apc.enable_cli=1

My Drive sync is now working very slowly, though photo import is not. Maybe there are API limits...

**Comment by luispinho** [comment]
Can confirm import is also taking some time for me, it's been around 5-6h and it imported about 7400 files (totalling 23GB). Very likely API restrictions indeed

**Comment by VeerNagda** [comment]
I also had the same issue. The way to start importing is to call background task explicitly using terminal. I noticed a single background job downloads around 200 photos.

Steps to run job
1)  alias occ="sudo -u www-data php /var/www/nextcloud/occ"
2) occ background:list
3) Find id for OCA\Google\BackgroundJob\ImportPhotosJob
4) occ background:execute <id>

![Screenshot 2024-04-16 113927](https://github.com/nextcloud/integration_google/assets/65171333/ac8877cf-30b6-4a09-b948-5acee67f2df8)
![image](https://github.com/nextcloud/integration_google/assets/65171333/29028482-33ad-4d52-bb19-f333c8578923)

**Comment by VeerNagda** [comment]
Task not being scheduled after executing a few tasks.
![image](https://github.com/nextcloud/integration_google/assets/65171333/3db361bd-2046-45e8-8a5b-30c5c53a0e61)
![image](https://github.com/nextcloud/integration_google/assets/65171333/e6dfc440-bfaf-4f27-b707-794b5b184112)

**Comment by marcelklehr** [comment]
If the job is not rescheduled you should check the nextcloud log for errors, it will only be rescheduled if it was successful
