### ISSUE TITLE
Calendar name is not sanitized before inserting it into database

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/integration_google#166]
### Which version of integration_google are you using?

1.0.9

### Which version of Nextcloud are you using?

master

### Describe the Bug

It seems the calendar name is not sanitized before inserting it in the database, which may be the reason for issues like https://github.com/nextcloud/calendar/issues/2911

https://github.com/nextcloud/integration_google/blob/11e10eb36ca7b11d5dff2153a4a0b6b56b1f8204/lib/Service/GoogleCalendarAPIService.php#L180

### Expected Behavior

Sanitize the name

### To Reproduce

Import a subscription from Google Calendar might do it?

**Comment by marcelklehr** [comment]
Thank you for reporting this @tcitworld
