### ISSUE TITLE
I can not login.

### ISSUE THREAD

**Issue by lyjlq** [nextcloud/integration_google#167]
### Which version of integration_google are you using?

2.2.0

### Which version of Nextcloud are you using?

28.0.3

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome, Edge and Firefox

### Describe the Bug

Hallo ich habe Google integration das erste mal installiert, und wollte mich das erste mal anmelden.
Ich bin auf die Adminitations seite gegangen (Datenmigration) und haben [Mit Google anmeldn] gedrückt. Ich erwartete die Googel anmeldeseite, aber ich bekam diese Fehlermeldung:
Kann mir einer Helfen?

Hello, I installed Google integration for the first time and wanted to log in for the first time.
I went to the administration page (data migration) and pressed [Sign in with Google]. I was expecting the Google login page, but I got this error:
Can someone help me?

Zugriff blockiert: Die Anfrage dieser App ist ungültig
Sie können sich nicht anmelden, weil diese App eine ungültige Anfrage gesendet hat. Versuchen Sie es später noch einmal oder wenden Sie sich an den Entwickler. [Weitere Informationen zu diesem Fehler](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
Wenn Sie Entwickler dieser App sind, finden Sie in den [Fehlerdetails](https://accounts.google.com/) weitere Informationen.
Fehler 400: redirect_uri_mismatch

![Bug Google intigration](https://github.com/nextcloud/integration_google/assets/163410901/71c991c8-19e9-49f8-bf31-0d5461a5bf52)

### Expected Behavior

 I was expecting the Google login page,

### To Reproduce

I went to the administration page (data migration) and pressed [Sign in with Google].

**Comment by marcelklehr** [comment]
You need to make sure that the redirect URL in the admin settings is correct based on what google tells you in their app dashboard.

**Comment by marcelklehr** [comment]
That's an awesome video, I'll add that to the repo!
