### ISSUE TITLE
Calendar Timezone display issue

### ISSUE THREAD

**Issue by duckunix** [nextcloud/integration_google#17]
First - Thank you for this! I have been struggling with how to tie Google Calendar to NextCloud, and most of the previous ways were messy and fragile. 

Second, I am using v0.0.9 of the app on v20.0.1 of NextCloud running from Linuxserver.io docker container, version-20.0.0.  I followed the nicely detailed directions on setting up the connections, and that is all working.  I went to import my first calendar, and it appears in my NextCloud Calendar 2.1.2 app fine, except that the time is displayed 5 hours early.  I can select an entry, and see that it is in the correct timezone (CDT, America/Chicago).  My docker image is running UTC, and the calendar is displaying the correct time.

Thoughts on what I need to adjust?

Thanks!

**Comment by eneiluj** [comment]
Thanks for the bug report! The problem is on the app side. It did not manage timezones correctly. It's fixed and available in v0.0.10 which I just released.

Could you try to import the same calendar again and tell me if it works for you now?

**Comment by duckunix** [comment]
That took care of it.  Thank you for the quick turn-around!
