### ISSUE TITLE
Import more than 100%

### ISSUE THREAD

**Issue by RobertHeim** [nextcloud/integration_google#174]
### Which version of integration_google are you using?

2.2.0

### Which version of Nextcloud are you using?

Nextcloud Hub 8 (29.0.3)

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)

### Describe the Bug

During migration I see at `https://nc.mydomain.de/settings/user/migration` more than 100% of file migration and I am wondering, what it syncs above the 100%?

![image](https://github.com/nextcloud/integration_google/assets/463840/d4e3c01b-2f58-44f4-9584-995580f52e92)

Makes me suspicious if the migration is working or not and I am afraid of data loss. How can I check it?

### Expected Behavior

I expect the migration to be done at 100%.

### To Reproduce

Maybe I messed up the cron because I called it multiple times but I would expect the `cron.php` to handle parallel executions. However, this is roughly what I remember I had done:

I had set up a fresh nextcloud installation via docker and no other apps, but the default ones (I disabled some that I don't need, like dashboard and user status). I setup the google integration (for files) and started the migration (for files only) and run the cron via `docker exec -u www-data nextcloud php /var/www/html/cron.php`. I stopped it, because I forgot to bring it in the background. I then tried to add `-d` with `docker exec -u www-data -d nextcloud php /var/www/html/cron.php` but found out several hour later, that the cron somehow did not continue running. I then added it to `crontab`:
```
# sudo crontab -e
*/5 *  *   *   *     docker exec -u www-data nextcloud php /var/www/html/cron.php
```

**Comment by RobertHeim** [comment]
It now completed at around 123%.

**Comment by pnpninja** [comment]
I noticed similar behavior for Google drive backup. 231%

**Comment by marcelklehr** [comment]
> Can you at least let us know if we can expect that the import was successful and we did not loose data?

The import does not take into account the percentage, the percentage is calculated after the fact. I don't think that it finishes prematurely.
