### ISSUE TITLE
Feature Request: scheduled pull

### ISSUE THREAD

**Issue by duckunix** [nextcloud/integration_google#18]
Would it be possible to schedule a pull/refresh from Google on a regular schedule?

**Comment by motsu35** [comment]
bumping this. I want to use this plugin to regularly sync a work cal to my devices. I standardized on nextcloud, and i have a few things in my house that display upcoming events from nextcloud (hence why I want to sync all my cal stuff into nextcloud vs doing it on a specific endpoint). Having a sync interval would make this perfect for my use case

**Comment by laxdragon** [comment]
+1 We need this! Having to manually click the import button to get new events from the calendar is a pain.
