### ISSUE TITLE
Export "Google documents" whenever it is possible

### ISSUE THREAD

**Issue by oncletom** [nextcloud/integration_google#21]
A "Google Document" (collaborative) cannot be downloaded, but they can be exported to various formats.

Google Documents can be "exported" via the [Files: export API](https://developers.google.com/drive/api/v3/reference/files/export). I used `application/vnd.openxmlformats-officedocument.wordprocessingml.document` as a MIME-Type to export a Google Doc into a `.docx` document.

So when a kind `drive#file` as a `mimeType` of `application/vnd.google-apps.spreadsheet`, `application/vnd.google-apps.document` or `application/vnd.google-apps.presentation`, they should be "exported" to a default format — could be `.xlsx`, `.docx` or `.pptx` (depend if you make it a user option, or set a hardcoded default).

- [Google Documents MIME types are listed here](https://developers.google.com/drive/api/v3/mime-types).
- [Exportable MIME types list is here](https://developers.google.com/drive/api/v3/ref-export-formats)

**Comment by eneiluj** [comment]
Thanks for reminding me it was possible. It's done and available in v0.0.12. I'm interested by your feedback!

I prefer exporting to odt, ods and odp which are much more open formats and will last in time.

**Comment by oncletom** [comment]
It totally works!

Thank you so much, I was not expecting this to land so soon 🙂 
It really helps migrate out of Google Docs, thanks a bunch.

**Comment by oncletom** [comment]
![image](https://user-images.githubusercontent.com/138627/97875804-37a7d300-1d1b-11eb-96a2-8f3df6a7e64e.png)
