### ISSUE TITLE
Allowed memory size of xxx bytes exhausted

### ISSUE THREAD

**Issue by oncletom** [nextcloud/integration_google#22]
I encounter this error when I run an export with `v0.0.11`.

```
[PHP] Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 798611624 bytes) at /var/www/html/3rdparty/guzzlehttp/psr7/src/Stream.php#92

at 2020-11-01T14:24:08+00:00
```

Sadly I do not have more informations to provide. But the export does not proceed further.

Nextcloud system report these figures:

- Version : 7.4.12
- Limite de mémoire : 512 MB
- Temps d’exécution maximal : 3600
- Taille de téléversement maximale : 2 MB

**Comment by eneiluj** [comment]
Yeah I guess it's because file contents are completely loaded in memory... They are now stored in a temporary file and loaded progressively by small chunks. It should do it. Could you try again with v0.0.12?

You're the best tester!

**Comment by oncletom** [comment]
So far so good!

**Comment by deanbarrow** [comment]
Hi @eneiluj,

I'm seeing this issue on both 0.14 and 0.15.
I've allocated 3G as the `memory_limit` in php, there are files larger than this but I assumed they'd be split into chunks.

```
Allowed  memory size of 536870912 bytes exhausted (tried to allocate 10485760  bytes) at  /var/www/html/custom_apps/integration_google/lib/Service/GoogleDriveAPIService.php#307
```

All the directories seem to be created however there are no files migrated.
Running within Docker if that helps.
