### ISSUE TITLE
Allow importing Google Calendars as subscriptions

### ISSUE THREAD

**Issue by strugee** [nextcloud/integration_google#25]
I'm not sure when exactly this should be offered. There are a couple scenarios I can think of:

* You own the calendar
* You don't own the calendar, but you have write access (presumably because it's a Google Calendar that someone else shared with you)
* You subscribed to the calendar in the Google Calendar UI

The last one seems like a great candidate for this feature. The others I'm not so sure. Maybe both options (import wholesale or subscription) should be offered? If you still expect the calendar to be modified on the Google Calendar side then this would be useful.

(As an example, maybe the calendar in the second scenario above changes frequently, but you almost never need to modify it so it'd be helpful to have it show up in your Nextcloud even if it's read-only. Or maybe you own the calendar, but it's shared with other people who won't migrate off Google Calendar, so the authoritative copy has to stay on Google Calendar.)

**Comment by eneiluj** [comment]
I initially started developing this app having this feature in mind...and I didn't find a way to get the iCal address of google calendars through the API. Didn't find a trick to generate it neither :grin:. I'll add the feature if we find a way. Do you know a way?

About when it should be possible: I think it would be nice to allow subscribing to any calendar, whatever the reason/context.

Thanks for the feedback!

**Comment by jessechahal** [comment]
Maybe the https://console.developers.google.com/apis/library/caldav.googleapis.com api would work?

**Comment by menelic** [comment]
Polite issue bump / request in 2021: Is there any update on this ? would indeed be great if google calendars could be imported as subscriptions - if this works it would ease the (partial) migration for those who can't make all their collaborators move off google immediately.

**Comment by eneiluj** [comment]
> Polite issue bump
:smile: 

It will most likely not as there is no way to determine the iCal subscription address through the google API.

Good news is that you can manually get the iCal address through google calendar web interface. From calendar list in left sidebar -> context menu of a calendar -> "settings and sharing" -> "Integrate calendar" -> "Secret address in iCal format". In Nextcloud Calendar, hit "new calendar" and select "New subscription from link", put the iCal address there.
Bad news is this is a read-only subscription.

Cheers
