### ISSUE TITLE
Issue with reverse proxy

### ISSUE THREAD

**Issue by Bergum** [nextcloud/integration_google#27]
Failed to import Google calendar: 502 Proxy Error Proxy Error The proxy server received an invalid response from an upstream server. The proxy server could not handle the requestReason: Error reading from remote server Apache/2.4.25 (Raspbian) Server at mynextcloud.myserver.com Port 443

**Comment by eneiluj** [comment]
Hmmm could you give more details?

What is your reverse proxy config? Are you using docker? etc...
Could you provide the content of `nextcloud.log` when this happens?

Thanks for the bug report.

**Comment by Bergum** [comment]
Im mot using docker.
Where do i find that log file?

**Comment by eneiluj** [comment]
In Nextcloud's data directory. In a standard install, it is directly in nextcloud's directory like `/var/www/html/nextcloud/data/nextcloud.log` for example.

Does the system running your Nextcloud server use a proxy to access the outside network (internet :grin:)?

**Comment by Bergum** [comment]
Ok.
I found it.
But first. 
The import sort of worked.
It imported the calendar items that is full days event, but not the rest.

How do i send the log file to you and not post it here?

**Comment by eneiluj** [comment]
You can put it there:
https://cloud.nextcloud.com/s/eQpsWcFwS23bdHK
Nobody will be able to see the file except me.

So I guess the proxy error is gone... Let's see what happens for the events that are not imported.

**Comment by Bergum** [comment]
Uploaded

**Comment by eneiluj** [comment]
Thanks, so first things first: There are a lot of errors mentioning you don't have enabled the APIs in google dev console. Then in the last lines, it seems those errors are gone, did you add the APIs in the meantime?

I would need to reproduce the problem to find its origin and solve it. Could you export the calendar in google calendar to an ical file (calendar item context menu on the left side of the screen => settings and sharing => export calendar). You can upload it in the same place than the log file.

If this data is too personal and you don't want to send it to me, I perfectly understand.

**Comment by Bergum** [comment]
Yes, i did enable the api's and did try again.

tor. 5. nov. 2020, 15:51 skrev Julien Veyssier <notifications@github.com>:

**Comment by Bergum** [comment]
Uploaded a little selection.

**Comment by eneiluj** [comment]
How did you filter to produce this file? It is not a valid ical file.

**Comment by Bergum** [comment]
Cut out 90% of the middle...

tor. 5. nov. 2020, 16:22 skrev Julien Veyssier <notifications@github.com>:

**Comment by eneiluj** [comment]
Well the file is not valid, I can't do much with this :grin:.

**Comment by eneiluj** [comment]
I manually fixed the file and kept 19 events, then imported it in google calendar, then imported it in Nextcloud through integration_google app and it worked fine. I guess the problematic part is not in those 19 events. I need the whole file to make sure I can reproduce the bug.

**Comment by Bergum** [comment]
Puttig my trust in you here... :-)


Med vennlig hilsen / *Yours sincerely*
__________________
Bjarne Bergum
Tlf 90123748



tor. 5. nov. 2020 kl. 16:33 skrev Julien Veyssier <notifications@github.com

**Comment by eneiluj** [comment]
Thanks a lot, my only goal is to get rid of this bug, I don't even read the calendar content.

I'm afraid I can't reproduce the bug with the exported file. Could you share the google calendar (in google website) with my test google account? `nyugglee@gmail.com`
This way I could reproduce the bug context and hopefully the bug itself.

It's the last thing I ask :grin:, sorry for all that and thanks a lot for your trust and patience.

**Comment by Bergum** [comment]
Updated to latest now, here is a new logfile.
Can't import contacts, files etc.

**Comment by eneiluj** [comment]
Contact issue should be solved in v0.0.21. Thanks.

The calendar issue (`General error: 1366 Incorrect string value: '\\xC3' for column 'value' at row 1`) might be related to the encoding on your server or your DB configuration.

Could you create an empty calendar, then move one problematic event, for example the one named `VS: TEAMm\u00f8te Kristiansand-Hovden med Stig` to this calendar and share it to `nyugglee@gmail.com`? I would see the real content of the event and could figure out why it is problematic. If you share the whole calendar, even better, I could check that everything runs fine.

I don't see any error with files and photos in your logs.

**Comment by Bergum** [comment]
Should we close this and continue on #31 ?

**Comment by eneiluj** [comment]
Let's do that.
