### ISSUE TITLE
addressing error in /settings/admin/connected-accounts "Make sure you set one "Authorized redirect URI" to"

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_google#3]
Hello,

An addressing error in /settings/admin/connected-accounts "Make sure you set one "Authorized redirect URI" to"
the application offers:
Make sure you set one "Authorized redirect URI" to https://nextcloud.domaine.com
when it should be
Make sure you set one "Authorized redirect URI" to https://nextcloud.domaine.com/apps/integration_google/oauth-redirect

Thanks,

**Comment by eneiluj** [comment]
Thanks for the issue. Did you actually try with the domain and witness it didn't work?
