### ISSUE TITLE
Not all files are imported from Google Drive

### ISSUE THREAD

**Issue by shr3k** [nextcloud/integration_google#33]
Ignore shared files: On.
Start of import: 957 files on Google Drive (10 GiB)
End of import: 422 files was imported from Google Drive.
Result is: Some (sub)folders created and empty, some (sub)folders are synced, pretty random pattern. Size of Google Drive import folder is 2.6 GB.

I have grep of nextcloud.log integration_google with loglevel 1, but nothing suspect... :-(

**Comment by eneiluj** [comment]
Thanks for the feedback.

One potential reason for that would be that the API does not provide the "webContentLink" for those files. In this case, the app checks if its mime type is document/spreadsheet/presentation. If it's none of that, it just ignores the file. I added some level 2 log in this case.

I don't see any other reason why this would happen... This API is the harshest I've ever seen :smile:.

v0.0.25 is out with those additional logs. Hope it helps...

**Comment by jrial** [comment]
Experiencing the same, both with Google Drive and Google Photo's. Tried multiple times. The import is also very slow. I've been staring at "1 file imported" for Drive for the past couple of hours.

**Comment by KonstantinGeist** [comment]
Same: I have thousands of photos, but it only imported 78 and stopped...

**Comment by marcelklehr** [comment]
Should have been fixed in the meantime.

**Comment by MaxErfurt** [comment]
I also have the same problem. Some folders seem to be synched completely. Others are empty.
