### ISSUE TITLE
Calendars imported several times / Undeletable Calendars

### ISSUE THREAD

**Issue by Blechpirat** [nextcloud/integration_google#34]
Hi,

I used very early versions of this add-on and have successfully imported calendars. BUT:

Back then, instead of just importing the calendar I clicked on, all calendars were imported. Trying to fix errors, I clicked on another calendar to import - and now I have calendars twice. Also, I can't delete them over the web interface.

How do I get rid of the calendars I got twice / don't want but can't delete?

TIA!

**Comment by eneiluj** [comment]
Hi, thanks for the feedback.

> Back then, instead of just importing the calendar I clicked on, all calendars were imported

It's weird, it was possible to import calendars one by one from the beginning...

I need more details to get what happened to you.

* Which app version (or approximate date) when producing calendars twice?
* What happens when you try to delete a problematic calendar in Calendar app? (If you could look for errors in `/var/www/.../nextcloud/data/nextcloud.log` when failing to delete)
* Does it work properly with v0.0.25? I mean can you import one single calendar and delete it afterwards? If not, same here, the error log could help.

I would not recommend to delete the calendars manually from the database. You'll never know if you cleaned everything related to the deleted calendar in all tables. Let's keep that as the last solution :grin:.

**Comment by Blechpirat** [comment]
Hey, thanks for replying this fast!

Must have been 0.0.7 (https://help.nextcloud.com/t/google-data-migration/95352/8?u=aelethian) - was sending you an error log regarding 0.0.5 back then, you might remember me.

First I tried deleting a calendar that won't update (one of the stuck ones) - no entry in the error log, just a short error in the web interface popping up.

Then I deleted a working google calendar - which worked fine, again without any entry in the log file.

Reimporting a google calendar I allready had in my system led to having most of the calendar entries twice.

So I deleted that calendar and reimported. That led to two entries in the log file:

{"reqId":"xx@xxxxxxxxxx","level":2,"time":"2020-11-26 T10:16:22+00:00","remoteAddr":"xxxx","user":"Blechpirat","app":"integration_google","method":"GET","url":"/index.php/apps/in                                                    tegration_google/photo-number","message":"Google API error getting album list to get photo number, no \"albums\" key in []","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}

{"reqId":"xx@xxxxxxxxxxx","level":2,"time":"2020-11-26 T10:17:40+00:00","remoteAddr":"89.14.3.250","user":"Blechpirat","app":"integration_google","method":"GET","url":"/index.php/apps/integration_google/photo-number","message":"Google API error getting album list to get photo number, no \"albums\" key in []","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}

I'm on v0.0.25 btw.

**Comment by Blechpirat** [comment]
Is there anything else I can do to help with that issue?

**Comment by eneiluj** [comment]
Without errors in nextcloud.log there is not much we can do. Could you set the log level to 1 in config.php, then try to delete a problematic calendar, then put the loglevel back to what it was and check if something related popped in the logs?

Anyway, if we find the error, it will most likely require some fix in the Calendar app.

Do you confirm that individual calendar import (and deletion :grin:) works fine with v0.0.25?

**Comment by Blechpirat** [comment]
Hey!

I have set loglevel to 1 and see stuff marked as "info" in my logfile now. Deleted the logfile in data/nextcloud.log and waited a bit - it created an entry that access to the logfile was problematic. Logging seems to work 👍 
Deleted the calendars - no entry at all.

I can confirm that calendar import and deletion as well as contact import works fine with 0.0.25.

**Comment by Blechpirat** [comment]
Hangon... there is more:
`Deprecated  event type for {"[object]  (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object]  (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object]  (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object]  (Sabre\HTTP\Response)","httpRequest":"[object]  (Sabre\HTTP\Request)","sapi":"[object]  (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over  20 items, aborting  normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object]  (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting  normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}:  null
-- | --
`
I mailed you the full logging file to your emailadress stated in your github profile.

**Comment by eneiluj** [comment]
Thanks a lot. I think this deprecation warning is not related to google integration app. It seems to happen when your Android client accesses caldav endpoints. I don't know why.

**Comment by Blechpirat** [comment]
That still leaves the question: How do I get rid of the calendars that are not working at all?

**Comment by eneiluj** [comment]
I don't know. If you manage to find related errors in the logs I could have a look.

**Comment by Blechpirat** [comment]
Could you point me at he location they are stored in the database?

**Comment by eneiluj** [comment]
They are in the `oc_calendars` table. If you just delete the calendar there, it's most likely enough but there might still be some related data in other tables. I guess it's not a big deal, it's just dead data :grin:.

**Comment by Blechpirat** [comment]
Thank you
