### ISSUE TITLE
Unable to import anything

### ISSUE THREAD

**Issue by maretodoric** [nextcloud/integration_google#35]
Hello everyone,

I've installed this app just fine to nextcloud. I've generated  Google Client ID/Secret from the project i already had on google and imported it.
I successfully connected my google account to nextcloud however when i try to import photos or files from drive, it just gets stuck at 0% and 0 files/photos.

Contact import was successful but not Photos and Files.

I'm using NextCloud 20.0.2 on CentOS 8 with PHP7.4.

Any help would be greatly appreciated .

**Comment by eneiluj** [comment]
Hey,

Drive and Photo import is done by background jobs. When you start importing in the UI, those jobs are scheduled and will be launched when your Nextcloud server runs its "cron" script.

Which background job method did you choose in Nextcloud (if you are the instance admin)? It's recommended to use the "Cron" one and set a system cron job running the cron.php file like it's explained [there](https://docs.nextcloud.com/server/20/admin_manual/configuration_server/background_jobs_configuration.html#cron).

With Ajax and Webcron methods, you're not guaranteed the process will regularly run.

**Comment by Bergum** [comment]
Are you behind a proxy?

**Comment by maretodoric** [comment]
@eneiluj 
Thank you, will try that now. It was set to Ajax by default, I've enabled posix extension, setup a cron job and changed to "Cron". So far i see processes in the background for php process getting stuck after running cron, i also saw a message "Last job execution ran 15 minutes ago. Something seems wrong." so I've briefly commented the cron to not make it heavy, will wait for current process to finish, maybe it has some catching up to do... I've configured it to run as "apache" user since that one is used in CentOS for httpd.

So either way, will wait for the further progress. Any idea where could i track the progress? I don't see new items in any of logs (nextcloud.log, httpd, syslog or php-fpm)

@Bergum 
Server itself - no. Well.. Kind of. I'm behind CG-NAT, have access to it via reverse vpn, long story. But i can access the server outside of my network just fine with this setup. Uploading of files also work when outside of my network.

**Comment by Bergum** [comment]
@eneiluj 
I am pulling my error.
When I stopped the import for 2 days, and restarted it after those two days, it worked.
Looks like i had to many requests to google, and was blocked for a while...

**Comment by djak250** [comment]
Necro-Issue. But I thought I'd share how I fixed my issue. I was having the same issue as OP. Somehow the user setting for `photo_import_running` was set to 1, even after something caused it to fail. I believe it gets set back to 0 under most pretenses, so I'm not sure how mine ended up being stuck on 1. I flipped it back to 0, and everything started syncing again. Hope it helps whoever else might be having this issue.

**Comment by lilfade** [comment]
> Necro-Issue. But I thought I'd share how I fixed my issue. I was having the same issue as OP. Somehow the user setting for `photo_import_running` was set to 1, even after something caused it to fail. I believe it gets set back to 0 under most pretenses, so I'm not sure how mine ended up being stuck on 1. I flipped it back to 0, and everything started syncing again. Hope it helps whoever else might be having this issue.

4 months that's been lagged up and I never checked the db. Good call, 50+gb downloaded overnight thanks to you!

**Comment by julien-nc** [comment]
174d2625e1987fbc89baa952c7bdffea168f17b8 should fix the issue of not being able to import anymore when a job has been "brutally" interrupted (server reboot, container restart, php process kill etc...).

Can someone try [v1.0.9-2-nightly](https://github.com/nextcloud/integration_google/releases/download/v1.0.9-2-nightly/integration_google-1.0.9-2-nightly.tar.gz)?

The idea is to have a 1h timeout after which a job is considered not running anymore even if the setting values say so.
I've successfully tested it in various cases on my side.

Approximate testing protocol :grin: :
* start importing a (large) drive (or photo) storage
* make sure the running background job is interrupted
* wait an hour
* click on the "Cancel Google Drive import" button in the personal settings (can also be done before waiting an hour)
* launch the import again

**Comment by lordratner** [comment]
> Necro-Issue. But I thought I'd share how I fixed my issue. I was having the same issue as OP. Somehow the user setting for `photo_import_running` was set to 1, even after something caused it to fail. I believe it gets set back to 0 under most pretenses, so I'm not sure how mine ended up being stuck on 1. I flipped it back to 0, and everything started syncing again. Hope it helps whoever else might be having this issue.

Pardon my ignorance, but how do I change this setting?

**Comment by lordratner** [comment]
> [174d262](https://github.com/nextcloud/integration_google/commit/174d2625e1987fbc89baa952c7bdffea168f17b8) should fix the issue of not being able to import anymore when a job has been "brutally" interrupted (server reboot, container restart, php process kill etc...).
> 
> Can someone try [v1.0.9-2-nightly](https://github.com/nextcloud/integration_google/releases/download/v1.0.9-2-nightly/integration_google-1.0.9-2-nightly.tar.gz)?
> 
> The idea is to have a 1h timeout after which a job is considered not running anymore even if the setting values say so. I've successfully tested it in various cases on my side.
> 
> Approximate testing protocol 😁 :
> 
> * start importing a (large) drive (or photo) storage
> * make sure the running background job is interrupted
> * wait an hour
> * click on the "Cancel Google Drive import" button in the personal settings (can also be done before waiting an hour)
> * launch the import again

Hi there. I'd like to try this since I'm having this issue.

How do I load the nightly version into Nextcloud?

Thanks

**Comment by julien-nc** [comment]
@lordratner In a similar fashion than https://github.com/julien-nc/cospend-nc#nightly
You can replace the app directory **or** use the occ command, don't do both :grin:.

**Comment by lordratner** [comment]
> @lordratner In a similar fashion than https://github.com/julien-nc/cospend-nc#nightly You can replace the app directory **or** use the occ command, don't do both 😁.

Thanks, learned something new. 

Is this fix incorporated in 1.0.9 that you just released?

**Comment by lordratner** [comment]
> @lordratner In a similar fashion than https://github.com/julien-nc/cospend-nc#nightly You can replace the app directory **or** use the occ command, don't do both 😁.

Thanks. Just got 1.0.9. Had to restart the server, but it's working now!

**Comment by Schachte** [comment]
Running 1.0.9 currently. I've rebooted server, queued job and reran system cron as www-data user. I'm still stuck at 0% for a 125GB google drive.

**Comment by mcortinas** [comment]
hi all,

I have the same issue and I think this is a pity due to i think it's a powerful tool in order to use more NextCloud and less Google. I tried several times and ways last 3 months without lucky... Sometimes I've seen some photo imported but less than 60.... the most of times stuck in 0% and 0 photos imported....

Let me show my environment
```
sudo -u www-data php /opt/nextcloud/occ status --output=json_pretty
{
    "installed": true,
    "version": "25.0.4.1",
    "versionstring": "25.0.4",
    "edition": "",
    "maintenance": false,
    "needsDbUpgrade": false,
    "productname": "Nextcloud",
    "extendedSupport": false
}
```
this is the volume to import
```
 >69542 Google photos (>64 GiB)

0 photos imported
Photo import background process will begin soon. You can close this page. You will be notified when it finishes.
```

I tried to increase php values without luchy....
```
upload_max_filesize=5G
post_max_size=5G
memory_limit=20G
```
1. Let me share nextcloud.log file starting Photo Importing with app - integration_google: 1.0.9 [afterPushButtonImportGooglePhotos.tar.gz](https://github.com/nextcloud/integration_google/files/10830938/afterPushButtonImportGooglePhotos.tar.gz)
2. I also upgraded integration_google to [v1.0.9-2-nightly](https://github.com/nextcloud/integration_google/releases/download/v1.0.9-2-nightly/integration_google-1.0.9-2-nightly.tar.gz) but I can see the menu changes from Data migration to Google Synchronization but I receive an error , it seems something related on javascript, let me attach an screenshoot.
![Screenshot_20230225_093955](https://user-images.githubusercontent.com/692263/221353670-a70d909a-3437-44e4-8a98-6ebf3554ad95.png)

**Comment by mcortinas** [comment]
Let me share more, I ran another instance of Nextcloud in my rapsberrypi4 but this time with docker, [i launched the all-in-one with docker-compose with more lucky, this time has been imported 4k images in 6hours, more or less....](https://github.com/nextcloud/all-in-one)

**Comment by etuckeriv** [comment]
> [174d262](https://github.com/nextcloud/integration_google/commit/174d2625e1987fbc89baa952c7bdffea168f17b8) should fix the issue of not being able to import anymore when a job has been "brutally" interrupted (server reboot, container restart, php process kill etc...).
> 
> Can someone try [v1.0.9-2-nightly](https://github.com/nextcloud/integration_google/releases/download/v1.0.9-2-nightly/integration_google-1.0.9-2-nightly.tar.gz)?
> 
> The idea is to have a 1h timeout after which a job is considered not running anymore even if the setting values say so. I've successfully tested it in various cases on my side.
> 
> Approximate testing protocol grin :
> 
>     * start importing a (large) drive (or photo) storage
> 
>     * make sure the running background job is interrupted
> 
>     * wait an hour
> 
>     * click on the "Cancel Google Drive import" button in the personal settings (can also be done before waiting an hour)
> 
>     * launch the import again

I am having this issue and am looking to try this solution. I have the nightly installed, but I'm not clear on how to "make sure the running background job is interrupted", how do I make sure it gets interrupted?

**Comment by marcelklehr** [comment]
This should be fixed in the latest release. Please comment here if you still experience this and we'll reopen this.
