### ISSUE TITLE
Unlimited quotas blocks imports

### ISSUE THREAD

**Issue by dommtardif** [nextcloud/integration_google#38]
For users with unlimited quotas, -2B is reported as free space which keeps user from importing data.
Tested this issue by giving user a large enough quota, which solves the problem.

**Comment by eneiluj** [comment]
Nice catch. I don't know why the free space value is never negative when quota is unlimited in my test instances.

It is now properly detected by getting the user quota value.

Could you confirm it works fine with v0.1.1 which I just released?

**Comment by dommtardif** [comment]
Should I expect v0.1.1 to be available through the appstore or should I attempt a manual install?

**Comment by eneiluj** [comment]
I'll tell you when it's available, sorry there's a delay I should have mentioned :grin:.

**Comment by dommtardif** [comment]
perfect, I'll wait for your Go and will update and test.

**Comment by eneiluj** [comment]
Some day are just not lucky. There was a problem in the release process because GitHub updated Php version in the Action containers... I had to fix it.

v0.1.2 is out now. It will appear in your Nextcloud once it refreshes the appstore data.

**Comment by Bergum** [comment]
Did not solve my problem, did you see my log?

**Comment by dommtardif** [comment]
my server has yet to refresh the appstore; will give an update when I tested.
BTW, i was curious and installed onedrive integration and the issue occurs in that plugin as well. Do you want me to open a seperate issue on that repo?

**Comment by eneiluj** [comment]
@Bergum This is unrelated to your problem. Let's talk about it in the related issue.

@dommtardif I already adapted Dropbox integration and will do OneDrive soon. No need to open additional issues. Thanks a lot.

**Comment by dommtardif** [comment]
I confirm the issue is fixed after update to 0.1.2 Good job!
