### ISSUE TITLE
Feature Request: configurable targetPath

### ISSUE THREAD

**Issue by cybik** [nextcloud/integration_google#39]
In the case of "big" imports such as Photos or Drive pull-downs, it would be interesting, maybe even "good", to allow the user to specify in which target directory they wish to import the files.

This way they can specify a directory that is pre-configured to not be synchronized to a downstream client.

Use Case I: I have my NextCloud instance, with 4 PC clients. If I start an import right now, all clients would see a new folder and start synchronizing it. By telling the import process to download from Drive/Picasa to a pre-created folder that is manually set to "do not sync", this issue is solved in its entirety.

**Comment by eneiluj** [comment]
Done, useful indeed. Thanks for the suggestion.

It will be available in v0.1.3 which is coming soon. It would be nice if someone could try this before the release. A nightly build is available in the appstore.

**Comment by cybik** [comment]
I'd gladly test it if I knew how to pull a nightly into my install :)

**Comment by eneiluj** [comment]
:grin: It is rather simple if you have access to your server's system. Delete the `/.../nextcloud/apps/integration_google` directory. Download the nightly archive and unpack it in `/.../nextcloud/apps/` so that there is a new `integration_google` directory. That's it.

To get back to official releases, just disable the app, delete the directory again, reload the app settings and click "download and install".

Feel free to ask for more details.

**Comment by cybik** [comment]
I needed to pull it into custom_apps but the instructions are the same for everything else :P

Okay so the new nit I need to say is "i should be able to create a folder in the selector", but I'm assuming this is part of another NextCloud component you are merely invoking, so I don't quite know where to post that UX issue ticket.

**Comment by cybik** [comment]
On the execution side I had to pull my dumb hack using a `watch -n 2` to poke cron.php on top of my hitting-per-2min docker healthcheck hack, but it's finally started importing drive files into the specified folder.

#shipit

**Comment by eneiluj** [comment]
Thanks for the quick feedback.

It might be better if the output dir value was always: `selected-directory/Google Drive`. What do you think?

**Comment by cybik** [comment]
Yes and no.

On one side, the "allow user to select the rootdir of where to download stuff" is generally a good idea if you're talking pure User Experience.

On the other, nerds like myself *are* going to raise a fuss and ask "why can't I just set it to a specific directory WHY ARE YOU MAKING ME DO A THING IN NOT EXACTLY THE WAY I WANT TO DO IT".

The choice is yours :P

**Comment by cybik** [comment]
Anyway. Feature works as requested. Anything beyond this point is merely UX optimisations. Thanks @eneiluj!
