### ISSUE TITLE
Error with google contact

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_google#4]
{"reqId":"74Xjv01O7NcQMStxwqwg","level":2,"time":"2020-10-02T15:13:16+00:00","remoteAddr":"x","user":"x","app":"integration_google","method":"GET","url":"/apps/integration_google/contact-number","message":"Google API error : Client error: `GET https://people.googleapis.com/v1/people/me/connections?personFields=names&pageSize=100` resulted in a `403 Forbidden` response:\n{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"People API has not been used in project 152656787343 before or it is dis (truncated...)\n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.8"}

**Comment by eneiluj** [comment]
Hmmm I would say : same as #5 but it might also be that you didn't add the APIs to your Google application. Did you?

This is the last part of the connected accounts admin settings explanation:

`Finally, go to "APIs & Services" => "Library" and add the following APIs: "Google Calendar API", "People API" and "Photos Library API".`
