### ISSUE TITLE
Photos outside of albums are not imported

### ISSUE THREAD

**Issue by teemue** [nextcloud/integration_google#41]
It seems that photos have to be inside albums to be imported. If this is intended / can't be changed, it should be mentioned in Data migration-page.

**Comment by jrial** [comment]
Haven't done an analysis to see whether it limits to albums only, but I also noticed that from the thousands of photos in my account, going all the way back to 2010, it only picks up 415.

**Comment by eneiluj** [comment]
Hi, thanks for the bug report. Photos outside of albums are imported fine on my side.

Which app version are you using?
Do you see related errors/warnings in nextcloud.log during the import?

**Comment by carlos-moreira** [comment]
This is happening with me as well, the endpoint:
index.php/apps/integration_google/photo-number was returning:
```
{
	"nbPhotos": 0
}
```

So I tried the suggestion @teemue said, I created an album and moved all my photos inside this album, after that the same endpoint started returning:

```
{
	"nbPhotos": 221
}
```

**Comment by Joshua2504** [comment]
Same issue. Why isn't this solved yet?

Literally impossible to switch to Nextcloud if you have 100.000 Photos in Google, because data export isn't an option as nextcloud will then sort files by their last modify date.

**Comment by talondnb** [comment]
Same problem here.

I get the following log entry:

Google API error getting album list to get photo number, no "albums" key in []

When I run a test and add some photos to an album, it appears correctly.

FYI, I have zero photos in any album (my photos are only sync'd via the google app on my phone) and the integration in nextcloud does not show any photo integration at all. When I ran the test above with a few photos, it finally appears when I go to the Data migration section in nextcloud.

**Comment by talondnb** [comment]
> As a workaround for this problem, you just need to create a single album on your photo library, this is suffice to make the photo import option to show up on nextcloud.

Any idea how I can move all of my photos to an album? I can't find a way to select all..

**Comment by ctml91** [comment]
Same issue here, too bad as I was hoping to use nextcloud for photo synchronization with google photos. Most of my photos aren't located in an album.

**Comment by marcelklehr** [comment]
Hello everyone! I've taken over maintenance of this app and will look into fixing this soon.

**Comment by marcelklehr** [comment]
I cannot reproduce this anymore. This has been fixed as far as I can see and reproduce with my own setup. Photos outside of albums can now be imported fine, even when there are no albums.
