### ISSUE TITLE
On import, set modified date to EXIF data (date photo taken)

### ISSUE THREAD

**Issue by dommtardif** [nextcloud/integration_google#42]
Since importing Google Photo into NC implies most of the time importing a library of photos, wouldn't be better to keep the modified date as the taken date so it's possible to sort photos by date? Further uploads (e.g. from NC phone app) should not be much of a problem since most of the time pictures will be uploaded at a time near taken date.

**Comment by jrial** [comment]
Agreed. When I use the Android app to auto-backup my local photos, dates are preserved. However, when importing from Google, the dates are nor preserved and 10 years of photos all show up under the current month.

**Comment by eneiluj** [comment]
Thanks for the issue.

v0.1.5-4-nightly is out and preserves files 'last modified date' and photos 'date taken'. Could you give it a try?

**Comment by dommtardif** [comment]
Well done! I confirm it works nextcloud 20.0.4, php7.4
