### ISSUE TITLE
Image previews from imported contacts not showing

### ISSUE THREAD

**Issue by hegocre** [nextcloud/integration_google#44]
After installing this app on my Nextcloud 20.0.4 instance and using it to import my contacts 3.4.2, I noticed than none of my contacts photos was showing on the contact list, at least not until I opened that specific contact, and also after refreshing it was gone again.

So after some research I found [this](https://github.com/nextcloud/contacts/issues/1140) github issue on contacts app where the same thing was happening, more specifically [this](https://github.com/nextcloud/contacts/issues/1140#issuecomment-502063540) comment.

So it seems that the version used on the PHOTO field of the vCard does not match its version. Afer looking at the expected PHOTO field and comparing it to the one generated by this app, I found that replacing 
https://github.com/nextcloud/integration_google/blob/4a07c0b19002baf5f3b594d65a5de935fec970d6/lib/Service/GoogleContactsAPIService.php#L185
with
```
$b64Photo = stripslashes('data:image/' . strtolower($type) . ';base64\,') . base64_encode($photoFile['content']);
```
does the trick, and now the previews are showing again. There's probably a better way to do this, but I don't know PHP so I am not able to think of it

**Comment by eneiluj** [comment]
Thanks a lot! I knew it wasn't correctly done for the reason you mentioned and also when facing problems getting contact photos in Maps app. But I couldn't find a simple way to solve that. Your solution is fine, it ensures VCard 4 compliance. It is included in v0.1.4 which was just released.

Cheers!
