### ISSUE TITLE
Google Drive imports don't preserve dates

### ISSUE THREAD

**Issue by jrial** [nextcloud/integration_google#46]
Similar to #42 - in Google Drive, I see the creation, modification and last access date of my documents. These dates are not preserved when importing into NextCloud. While I don't care about the last access date, creation and last modification dates are somewhat important. Assuming a fix is forthcoming for #42, I propose to apply that fix to the Document import as well, if possible.

Google Drive:

![image](https://user-images.githubusercontent.com/570247/104119302-b24e2980-532e-11eb-9220-2a461b781382.png)

NextCloud, after import:

![image](https://user-images.githubusercontent.com/570247/104119275-921e6a80-532e-11eb-9a83-e642688b3f9e.png)

**Comment by eneiluj** [comment]
Thanks for the issue.

v0.1.5-4-nightly is out and preserves files 'last modified date' and photos 'date taken'. Could you give it a try?
