### ISSUE TITLE
Credentials  OAuth consent screen different to installation doc

### ISSUE THREAD

**Issue by ggrobi** [nextcloud/integration_google#48]
Tried following the installation documentation but the Google interface is completely different from documentation. Is there an updated version or am I in the completely wrong area? See screenshot
![image](https://user-images.githubusercontent.com/14949361/105570794-8192d900-5d9f-11eb-817b-d6596bfe1246.png)

**Comment by eneiluj** [comment]
Hi, there is no need to configure an "OAuth consent screen". The procedure is up to date, I just checked in google console interface. You just need to go in "Credentials" (left sidebar) and follow the instructions in Nextcloud "connected accounts" admin settings section.

Any better?

**Comment by crcerdas** [comment]
Same happens to me @ggrobi  , no way to follow up the procedure.  Can you Double chek @eneiluj ?
Thnks

**Comment by eneiluj** [comment]
I tried to create a new google account and set it all up. For some reason, when visiting `https://console.developers.google.com` I'm redirected to `https://console.cloud.google.com` and the consent screen configuration becomes mandatory...

I've managed to configure everything and get this app work.

They make it awfully complicated... And there are a lot of restrictions. Make sure you read the explanations about "Publishing status" and "User type".

So you need to create an OAuth app.
Set the "user type" to "external".
You can leave the "App domain" section empty.
If your Nextcloud domain is `my.nextcloud.example.org`, then set the "Authorized domains" field to `example.org`. (just the top domain and the first subdomain.
Then, when asked for the scopes, enter this in the "Manually add scopes" field:
```
openid
profile
https://www.googleapis.com/auth/calendar.readonly
https://www.googleapis.com/auth/calendar.events.readonly
https://www.googleapis.com/auth/contacts.readonly
https://www.googleapis.com/auth/photoslibrary.readonly
https://www.googleapis.com/auth/drive.readonly
```
and press "Add to table".
In "Test users" section, add yourself (your google account) as a test user.

Once that is done, you should be able to follow the procedure about the "Credentials" section.
Don't forget to "enable" the APIs in the "Library" section.
Good luck.
Feel free to ask questions :grin:.

**Comment by Redsandro** [comment]
This was confusing and difficult to do. Documentation was not useful. I did it like this:

**Google Cloud Platform**

- Create new Nextcloud project
  - Create new OAuth Consent Screen
    - Add gmail address of Nextcloud user to test users
  - Add APIs to Nextcloud project
    - People API
    - Google Drive API
    - Photos Library API
    - Google Calendar API

**Nextcloud Instance**
    
- Settings > Connected Accounts > Google Integration
- Settings > Data Migration > Google Login

**Comment by netzwerch** [comment]
I'd like to add, that I also needed to activate the needed API's (People, Drive, Photos, Calendar) here:
https://console.cloud.google.com/apis/library
Simply adding the scopes was not enough.

**Comment by celiaudi** [comment]
Hi all, I've followed the instructions above, activate the 4 API, defined the scope as the readonly  options for each and was able to connect to Google successfully, but the only options to migrate data are People and Calendar. Any ideas? Thanks in advance.
![Captura de tela 2021-11-16 123917](https://user-images.githubusercontent.com/88104575/142016821-d3aff296-4e0d-4305-967f-234bddf5b3e2.png)

**Comment by paulvt** [comment]
> In "Test users" section, add yourself (your google account) as a test user.

But does that mean I have to add every user of my Nextcloud instance that might want to migrate their stuff as a test user?!
I tried to get the app out of Testing status using using "Publich app" under the publishing status of the OAuth consent screen but that just requires to meet some outrageous demands.
