### ISSUE TITLE
Import Calendar Event-Colors 

### ISSUE THREAD

**Issue by burnhard93** [nextcloud/integration_google#49]
Would it be possible to import the colors from Google Events? That would be amazing!
Thanks!

**Comment by eneiluj** [comment]
I didn't do it because Google calendar API does not return color names so it requires some processing to get a VCard valid value. It's now done and available in v0.1.6. Could you try it and confirm it works fine?

**Comment by Brucki** [comment]
Thank for your efforts, nice to hear :)

Unfortunately got 2 Errors:

While loading the calendars:
`Fehler beim Abrufen der Google Drive-Informationen: "ServerException|ClientException, message:Client error: 'GET https:\/\/www.googleapis.com\/drive\/v3\/about?fields=%2A' resulted in a '403 Forbidden' response:\n{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"usageLimits\",\n \"reason\": \"accessNotConfigured\",\n \"message\": \"Acces (truncated...)\n status code: 403"`

When I click on Import:
`This application requires JavaScript to function properly. Please activate JavaScript and reload the page. `
But Javascript is enabled

**Comment by eneiluj** [comment]
The first error is not related with calendars. It seems you have reached the API usage limit...

Could you check if there are any errors popping in your nextcloud.log when you click on a calendar import button? This is most likely mistake on my side. I does not happen to me though. Let's find out what it is and fix it.

**Comment by Brucki** [comment]
Ah now i got it, it's my first time using Nextcloud. :)

So i get this Error when i click on import:
`Exception: Class 'Ortic\ColorConverter\Color' not found`

**Comment by eneiluj** [comment]
Thanks for your feedback. It's a release problem. I don't know why the Php library was not fully included. Let me investigate on that and publish another release soon.

**Comment by eneiluj** [comment]
Ok I got it. When producing a release, some files/folders are excluded like the `src` directory which is useless for the release :grin:. Thing is it was also excluding all directories named `src` wherever they are in the app. This is fixed and v0.1.7 is on its way. it should be there in 10 minutes. I'm obviously interested in your feedback :smile:.

**Comment by burnhard93** [comment]
Still  0.1.6 in my Apps, is there any way to force App updates? :/

**Comment by eneiluj** [comment]
You should see it in a few minutes. Appstore refresh is done by a background job. You can execute the cron.php script manually if you want.

**Comment by burnhard93** [comment]
It's working like it should. Thanks man!

**Comment by eneiluj** [comment]
You're welcome. Thanks for the suggestion and for your enthusiasm!
