### ISSUE TITLE
Data Migration stuck

### ISSUE THREAD

**Issue by seanodea** [nextcloud/integration_google#51]
Is there some limit? Is it working on some giant video? What queries can I run to check what it's doing? I do not receive a 429 from google in data/nextcloud.log. The word google doesn't appear there so I can't determine the status of what the app is doing.

**Comment by eneiluj** [comment]
Did you try to wait to see it at some point the import process continues?

Each photo import job stops after having downloaded 500 MB and schedules the next job.
`500 / 2250 = 0.222`
If the average photo size is 222 KB, it just seems that the first import job finished and you have to wait for the second one to start.

Are you using the "Cron" background job method? (Admin Basic settings section)
If yes, how often is the cron.php script executed?

**Comment by Malspherus** [comment]
I have the same problem, download hasn't been moving for a few days now. In my case I am well over the 500MB limit (showing 2.7GB in the folder), my cron is also running properly.

![Screenshot_2021-02-19 Einstellungen - Nextcloud](https://user-images.githubusercontent.com/5000275/108505489-c7b45d00-72b7-11eb-8b71-6d40341d554d.png)

**Comment by seanodea** [comment]
@eneiluj I'm running the cron via cronjob in linux. It runs successfully and every 5 minutes. I just reauthed with google it's sitting at 279 photos. How does it handle large photos, videos or gifs?

**Comment by seanodea** [comment]
Next day 279 still. I think it's downloading something larger than 500MB and doesn't complete.

**Comment by seanodea** [comment]
279 still, a gagillion successful cron runs later. At this point, I'm considering it broken.

**Comment by seanodea** [comment]
I raised the 500MB limit to 99 Terrabytes, set my cron pod's spec.startingDeadlineSeconds to ten, canceled and reinitiated import, seems to be working now.

I recommend that you schedule in terms of the number of files and not size, preventing concurrent crons in code. That might end up being slower, but slower and working is better than faster and not working.

Really great software by the way, looking through the code I'm astonished the care put into it.

**Comment by eneiluj** [comment]
@seanodea Hi, thanks for the interest you put in this issue and this project.

I had a quick look at the job management code and it's true that having concurrent jobs running is the issue here. I published a nightly build with a fix attempt (v1.0.1-1-nightly). Could you try it?

In this nightly, jobs just quit if there is another one currently running for the same user. This way we can keep the 500MB limit.

**Comment by ProgramComputer** [comment]
I have the same issue but different number of photos.

**Comment by git529** [comment]
Can anyone here confirm if this app will import the photos with the metadata included in the jpg files? As you know Google Takeaout strips the metadata and puts into a separate json file.

I am looking for an easy way of backing up my Google Photos including the metadata.

**Comment by lkthomas** [comment]
> Can anyone here confirm if this app will import the photos with the metadata included in the jpg files? As you know Google Takeaout strips the metadata and puts into a separate json file.
> 
> I am looking for an easy way of backing up my Google Photos including the metadata.

this is not a forum, if you have another question unrelated to the topic, open another issue to discuss there.

**Comment by marcelklehr** [comment]
> How can I diagnose what's going on?

Could you try to find out the internal state of the app? Try the following occ command: `php occ user:setting YourUsernameHere integration_google`. Make sure to avoid pasting sensitive information here.

**Comment by shalak** [comment]
Huh. I re-authorized the app and triggered the process again. Everything went smoothly this time. I guess somewhere between 25.0.3 and 25.0.6 my issue was resolved.
