### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by bakeromso** [nextcloud/integration_google#52]
Hi everyone,

I'm trying to set up the integration but it just won't work. I've followed the steps: created a project in Google Dev, enabled the API's (calendar, drive, people and photos), I set up a redirect URI.
As a redirect URI I filled in the following: https://192.168.2.4.nip.io/index.php/apps/integration_google/oauth-redirect
So the only difference between this and the suggest URL is that I added .nip.io, since my Nextcloud is not internet facing

I tried it with the original URL as well, that didn't work. I tried some nonexistant domain name, and then modified the  /etc/hosts file on the machine I am working from so to redirect nonexistantwhatever.com to 192.168.2.4 but that also didn't work.

I just keep getting the following error:
Authorization Error
Error 400: invalid_request
device_id and device_name are required for private IP: https://192.168.2.4/index.php/apps/integration_google/oauth-redirect

I logged out and in several times on both Google and Nextcloud account, and I triple checked that client-id and client-secret are filled in (those that both are prompted when the oauth was just created, and when you edit the credential it shows in the right upper corner)

I am out of ideas what to try next, I hope anyone has another suggestion!

**Comment by eneiluj** [comment]
> I added .nip.io, since my Nextcloud is not internet facing

Why? The redirection is going to happen in your browser, it does not matter if your Nextcloud is accessible from the Internet or not.

I need more information to understand what happens to you.

* When and where exactly are you getting the 400 error? Do you even see Google authentication page or is it failing directly when you press connect on Nextcloud side?
* Could you check if something pops up in nextcloud.log when you try to authenticate?

**Comment by bakeromso** [comment]
thanks for your swift reply!
The reason I'm adding nip.io is that otherwise Google won't let me add the URI. It has the requirement that it must be a public IP and end in .com or some sort. So this is a way to circumvent that.

I'm getting the 400 error as soon as I hit "Connect to Google" from the "Data migration" tab under user settings. I do indeed land on a Google page, https://accounts.google.com/signin/oauth/error?authError=Cg9pbnZhb.... 

So it seems to be failing on the google site. Logging tab in Nextcloud shows nothing when I try to make the connection to google.

Is there anything else I can provide to make this easier?

**Comment by eneiluj** [comment]
Ok right, so if you set https://192.168.2.4.nip.io/index.php/apps/integration_google/oauth-redirect as the redirect URI on Google side, https://192.168.2.4.nip.io has to be the URL with which you access your Nextcloud when visiting the Data migration settings. Is it?

Google is most likely complaining because the integration app passes an incorrect redirect URI: one that is generated from your current page location.

**Comment by bakeromso** [comment]
> Actually I accessed the nextcloud server at
> 
> https[https://192.168.2.4.nip.io]://192.168.2.4[https://192.168.2.4.nip.io]
> That's probably why it is going wrong! Thanks so much I will try this as soon as I get back to the server. To be continued!

5 Feb 2021 15:40:32 Julien Veyssier <notifications@github.com>:

**Comment by bakeromso** [comment]
It works now! You were right, the page I'm accessing nextcloud at must be the same as the redirect uri. I'll close this comment. Is there somewhere I can add to the documentation? Here's some steps I did what I think would be of value to others:

1. In the Google API website, you are prompted to make an Oauth consent screen. Here you can add test users to your "application". You have to do this! Otherwise you can't use the "application" you are making, so you still won't be able to connect to google from this Nextcloud integration.
2. Choose a URI that you actually access the server from. If your nextlcoud server is at 192.168.1.2 then here you can fill in 192.168.1.2.nip.io or 192.168.1.2.nix.io or any similar service. I wasn't how this was managed privacy wise, so I ended up editiing the hosts file (see next step). Going with these .nix.io like extensions gives you the benefit that you do not need to mess with the following step. Make sure to still fill in the full redirect uri, `https://whateveryouwant.org/index.php/apps/integration_google/oauth-redirect` 
3. edit your /etc/hosts file and add the line 
```192.168.1.2  whateveryouwant.org```
4. In your nextcloud machine, add your new domain to the trusted domains. Open `config.php` (for me, located at `/var/www/nextcloud/config/config.php`. On the line `'trusted_domains'` add your domain, `whateveryouwant.org` in my case, and `192.168.1.2.nix.io ` if you went for that option
5. Now access your server on your domain! So go to `https://whateveryouwant.org` or what domain you chose and from there go to options, data migration, connect to Google. 

Oh and possibly this is usefull to anybody, but I hoped I would be able to view my Google Calendar in Nextcloud. However, the way I understand it now is that calendars are copied from Google into your Nextcloud. However they are not in sync; changes in Google Calendar are not visible as only a one time copy as made into your Nextcloud Calendar.
