### ISSUE TITLE
Google connection succeeded but with an error...

### ISSUE THREAD

**Issue by dennco** [nextcloud/integration_google#55]
Hi,

can someone help me ? i got always this error:
Fehler beim Abrufen der Google Drive-Informationen: "ServerException|ClientException, message:Client error: `GET https:\/\/www.googleapis.com\/drive\/v3\/about?fields=%2A` resulted in a `403 Forbidden` response:\n{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"usageLimits\",\n \"reason\": \"accessNotConfigured\",\n \"message\": \"Acces (truncated...)\n status code: 403"✖

i can not find my mistake..

**Comment by jdaviescoates** [comment]
There are various things you need to have done to get it to work

Verify the ownership of the domain in Webmaster Central
Enable the relevant APIs within the App
Add the Scopes of the relevant APIs within the App
and possibly more I can't remember right now.

Have you done all three of those at least? :)

**Comment by neoKushan** [comment]
> There are various things you need to have done to get it to work
> 
> Verify the ownership of the domain in Webmaster Central
> Enable the relevant APIs within the App
> Add the Scopes of the relevant APIs within the App
> and possibly more I can't remember right now.
> 
> Have you done all three of those at least? :)

I know this is going to be a dumb question...but is any of this documented anywhere?

**Comment by eneiluj** [comment]
All instructions related to the OAuth app creation on google side are in "connected account" NC admin settings section.
Glad you figured it out.
