### ISSUE TITLE
I get multiple notifications about importing Google Drive files every time I turn my computer on

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/integration_google#57]
I recently used this to import all my data from Google - it worked great! But I now get notifications about Nextcloud successfully importing Google Drive files every time I turn my computer on (and then throughout the day too, I guess every time Nextcloud Desktop checks it's in sync). I'm not sure if this is an issue with this Google Integration app or with the Desktop Client, but I'd rather not get notifications telling me the exact same thing over and over again :)

**Comment by eneiluj** [comment]
Sorry for the late reply.
Any news about that?
I guess notifications will continue popping until you dismiss them in the web UI.
This app procuces classic notifications, nothing fancy, just like any other app.
Does it only happens with this app's notifications?
