### ISSUE TITLE
Synchronization with Google Drive does not continue after an error + size calculation

### ISSUE THREAD

**Issue by StaceZ** [nextcloud/integration_google#60]
Very good app! Thanks!
I have successfully synced my calendar and address book! But there were problems with google drive; (

Google Drive show that I have 9.9GB used. Nextcloud show only 6GB.

I've tried syncing twice:
The first time syncing is over 55% because it ran out of disk space.
Which it was downloaded just 1.5GB

I added disk space, but sync did not continue.
I canceled the job, deleted the directory and restarted it, but the sync still didn't start.

I waited for several hours, but it said that the synchronization will start soon, and 0 files are synchronized now

Every 3 minutes (when cron.php started) a line "InvalidArgumentException: Section with the same ID already registered: migration, class: OCA\Google\Settings\PersonalSection" appears in the log, but nothing else happens. 

I stopped the job, deleted all personal data from the database (delete from oc_preferences where userid='\<my userid\>' and appid='integration_google';), then started the job again and it started working. 

Synchronization stopped again last night. There was an error in the log that one of the files in Google Drive was locked. I deleted this file, but syncing does not continue.

Now I see: "937 files in Google Drive (6 GiB),1849 files imported (197%), Last Google Drive import job at 13 may 2021, 18:44"

This is the text I saw last night, and almost 20 hours have passed.
Local "Google Drive" directory size only 5.5GB.

In the log file, an entry for "Section with the same ID already registered" still appears every three minutes.

Can I continue syncing without deleting database entries and downloaded files?
How?

**Comment by StaceZ** [comment]
"occ app:update --allow-unstable integration_google" does not help me ;(I use NC 21 also, and last version of integration_google app if v1.0.2 ж(

**Comment by eneiluj** [comment]
Yeah sorry, this app was adapted to new Nextcloud internal API stuff. Further releases will only be available for NC >= 22.

**Comment by marcelklehr** [comment]
Should be fixed with the latest releases.
