### ISSUE TITLE
App "Google integration" cannot be installed because it is not compatible with this version of the server.

### ISSUE THREAD

**Issue by xxxcrow** [nextcloud/integration_google#67]
Trying to install nightly, or at least the latest stable
Option -f doesn't change anything, is there any requirement for nextcloud instance?

**Comment by eneiluj** [comment]
No requirement.

* v1.0.4-2-nightly works with NC 22
* v1.0.3 works with NC 22
* v1.0.2 works with NC 20 and 21

Which version of Nextcloud are you using?
If you are running 20 or 21 or 22 you should be able to install the app from the app settings.

**Comment by xxxcrow** [comment]
My version is NC 21.0.3
The newest available version of Google integration on **App marketplace** for me is 1.0.2

**Comment by eneiluj** [comment]
:grin:
