### ISSUE TITLE
The value {amount} in the text string

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/integration_google#7]
Does this `{amount}` in the text string represent a numeric value?

https://github.com/nextcloud/integration_google/blob/f0b9eda1c25ab7bdbf206ba556761659ee273dc0/src/components/PersonalSettings.vue#L30

https://github.com/nextcloud/integration_google/blob/f0b9eda1c25ab7bdbf206ba556761659ee273dc0/src/components/PersonalSettings.vue#L83

https://github.com/nextcloud/integration_google/blob/f0b9eda1c25ab7bdbf206ba556761659ee273dc0/src/components/PersonalSettings.vue#L96

If so, the "contacts" and "photos" should be singular and plural.

**Comment by eneiluj** [comment]
The chances to have only one photo or one contact are very very low. Let's keep a plural.

**Comment by Valdnet** [comment]
@eneiluj What about 2 contacts or photos? They are also inflected in some languages.

> The chances to only have one photo or one contact are very very low.

But it can occur.
