### ISSUE TITLE
Google Branding Guidelines for App Verification

### ISSUE THREAD

**Issue by tabp0le** [nextcloud/integration_google#70]
I'm attempting to get my Oauth app "Verified" by Google, as I have thousands of users, and the 100 user limit imposed by Google for unverified apps with restricted scopes is a problem. 

Google has informed me the app is in violation of their branding guidelines and therefore cannot be approved.

Branding Guidelines: https://developers.google.com/identity/branding-guidelines

I request you please update the "Connect to Google" button to comply with Google's guidelines.

Thanks,
Tab

The following is the e-mail I received from Google:

> Dear Developer,
> 
> Thanks for your patience while we reviewed your project.
> 
> The Google sign-in button in your YouTube link is not compliant with the Google sign-in branding guidelines. (Please see the attached screenshot)
> 
> Please update the Google sign-in button so that it complies with the Google sign-in branding guidelines.
> 
> Note: After updating the Google sign-in button, please provide an updated YouTube link in order to proceed with the approval process.
> 
> If you have any other questions, you can read the OAuth Application Verification FAQ or reply directly to this email.
> 
> Thanks,
> The Google Cloud Trust & Safety Team

**Comment by paz** [comment]
You could change it locally while you wait, seems like a simple fix

**Comment by DuncanLithgow** [comment]
This can be closed. The mentioned changes are now in the stable release.

**Comment by eneiluj** [comment]
Thanks
