### ISSUE TITLE
 Update to some Google Drive file links, admin decision recommended before July 23, 2021 

### ISSUE THREAD

**Issue by tacruc** [nextcloud/integration_google#72]
Hi,
 I just revived an email about 
https://workspaceupdates.googleblog.com/2021/06/drive-file-link-updates.html.
Does this require changes on this app?

**Comment by tabp0le** [comment]
Yes it will need changes

**Comment by tacruc** [comment]
I July 2021 is long a go. So I guess  this is outdated.
