### ISSUE TITLE
[Question] Does "import" mean "one-time import" or will it keep things up to date?

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/integration_google#77]
The readme does not make the scope of this app clear to me. Does it do a one-time import, load all your google stuff into nextcloud so that you can migrate away from using those google services, or does it synchronize your nextcloud with google and keep it up to date?

I require the latter. My work requires me to use Google calendars, but I would much prefer to have all my calendars synchronized into one place: nextcloud. I do not have the private link to the google calendar (so I can't import it in the normal way) and I don't have write access to the calendars so I can't test if it will be updated when something changes.

Sorry if this is a stupid question. Maybe if it's confusing at least to me the README could be made more clear?

**Comment by MarcelRobitaille** [comment]
It looks like there are already background jobs for Drive and Photos. Could one be added for Calendar?

**Comment by MarcelRobitaille** [comment]
For anyone who thumbsed this up, I have implemented a background job that will keep the calendar up to date. it also deletes old calendar events so they don't get cluttered up. https://github.com/MarcelRobitaille/integration_google

**Comment by Niccolo-Marcucci** [comment]
@MarcelRobitaille your implementation is exactly what i was looking for . Do you think you will be able to push it mainstream or would it cost you too much time?

**Comment by MarcelRobitaille** [comment]
Hi @Niccolo-Marcucci. I don't know what you mean push it mainstream. I don't have access to merge into this repository, if that's what you mean.

**Comment by chaddy314** [comment]
Very Nice @MarcelRobitaille !

> Hi @Niccolo-Marcucci. I don't know what you mean push it mainstream. I don't have access to merge into this repository, if that's what you mean.

You could create a [Pull Request on the upstream repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by MarcelRobitaille** [comment]
I did not create a pull request because I think my implementation is not very polished, and it seems like this plugin intentionally only migrates from Google, it does not seem to be intended to continuously sink. I guess it doesn't hurt to open the PR and then the maintainers can weigh in on if they're interested and what changes would be required.

**Comment by MarcelRobitaille** [comment]
Let's continue this discussion in https://github.com/nextcloud/integration_google/pull/93.

**Comment by Niccolo-Marcucci** [comment]
> I did not create a pull request because I think my implementation is not very polished, and it seems like this plugin intentionally only migrates from Google, it does not seem to be intended to continuously sink. I guess it doesn't hurt to open the PR and then the maintainers can weigh in on if they're interested and what changes would be required.

I meant exactly this! I've read in you repo you didn't feel quite confident on your code to be suited for pull request, but maybe it doesn't require as much work. Although i'm no developer to say that.

> Let's continue this discussion in #93.

copy that
