### ISSUE TITLE
Photos import only work when there is at least 1 album

### ISSUE THREAD

**Issue by Niveshkrishna** [nextcloud/integration_google#80]
Import photos section is not visible when a user has photos in Google photos app but does not have at least one album. This section is only enabled when there's at least one album in Google photos app.

It'd be interesting to have photos section available even when there isn't any album but has photos. It that is not possible, at least a warning message to user that "At least one album must be present to import photos" could be helpful

**Comment by akhil1508** [comment]
This can be closed imo @Niveshkrishna @eneiluj .
