### ISSUE TITLE
Update README to guide users on Google app verification

### ISSUE THREAD

**Issue by Niveshkrishna** [nextcloud/integration_google#81]
In order to use this application in production, one must get their oauth app verified from Google. It could be overwhelmingly confusing for new developers who have not used GCP. 

A simple procedure on how to activate, which scopes to enable and other info could be provided.

What @eneiluj and @Redsandro mentioned [here](https://github.com/nextcloud/integration_google/issues/48#issuecomment-775293092) is quite useful for anyone who is looking for verification process

**Comment by marcelklehr** [comment]
The app admin settings now provide a guide:

![image](https://github.com/nextcloud/integration_google/assets/986878/ea344243-a3b8-4cfa-9827-d70d5f27fcb7)
