### ISSUE TITLE
Can’t re-import deleted calendar

### ISSUE THREAD

**Issue by chatelp** [nextcloud/integration_google#99]
Using Nextcloud 23.0.2

I accidentally deleted in Nextcloud a calendar I had imported from google using this tool. Unfortunately each time I now click on the same import button for this particular calendar, it says « 0 events successfully imported », as if the calendar was not really deleted from Nextcloud.

Any ideas?

**Comment by motsu35** [comment]
Also having this issue. Going into the admin page and removing the integration then reinstalling does not fix this.

**Comment by julien-nc** [comment]
A calendar is not really deleted until the calendar trashbin has been cleared.
Feel free to reopen if needed.
